In [201]:
import pandas as pd
import numpy as np

In [202]:
ride_ids_df = pd.read_csv("ride_ids.csv")
driver_ids_df = pd.read_csv("driver_ids.csv")
ride_timestamps_df = pd.read_csv("ride_timestamps.csv")

In [210]:
#convert to datetime
ride_timestamps_df["timestamp_c"] = pd.to_datetime(ride_timestamps_df["timestamp"])

In [204]:
#ride_timestamps_df
#table_arrived_at['timestamp_c'].astype('datetime64[D]').dtype - pd.to_datetime(table_requested_at['timestamp_c'])
# new data frame with split value columns 


#drop values that have n/a
ride_timestamps_df.dropna(inplace = True) 
ride_timestamps_df = ride_timestamps_df.loc[ride_timestamps_df['ride_id'] != "72f0fa0bd86800e9da5c4dced32c8735"]

#split the timestamp to individual columns of 
# year | month | date | hour | minutes | seconds
new = ride_timestamps_df["timestamp"].str.split("-", n = 2, expand = True) 
ride_timestamps_df["Year"]= new[0].astype(str).astype(int)
ride_timestamps_df["Month"]= new[1].astype(str).astype(int) 
ride_timestamps_df["Date"] = new[2]
new = ride_timestamps_df["Date"].str.split(" ", n = 1, expand = True) 
ride_timestamps_df["Date"] = new[0].astype(str).astype(int)
ride_timestamps_df["Other"] = new[1]
new = ride_timestamps_df["Other"].str.split(":", n = 2, expand = True) 
ride_timestamps_df["Hour"] = new[0].astype(str).astype(int)
ride_timestamps_df["Minutes"] = new[1].astype(str).astype(int)
ride_timestamps_df["Seconds"] = new[2].astype(str).astype(int)

# ride_timestamps_df = ride_timestamps_df.drop(["other", "Other"], axis = 1)

ride_timestamps_df

,ride_id,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds
0,00003037a262d9ee40e61b5c0718f7f0,requested_at,2016-06-13 09:39:19,2016-06-13 09:39:19,2016,6,13,09:39:19,9,39,19
1,00003037a262d9ee40e61b5c0718f7f0,accepted_at,2016-06-13 09:39:51,2016-06-13 09:39:51,2016,6,13,09:39:51,9,39,51
2,00003037a262d9ee40e61b5c0718f7f0,arrived_at,2016-06-13 09:44:31,2016-06-13 09:44:31,2016,6,13,09:44:31,9,44,31
3,00003037a262d9ee40e61b5c0718f7f0,picked_up_at,2016-06-13 09:44:33,2016-06-13 09:44:33,2016,6,13,09:44:33,9,44,33
4,00003037a262d9ee40e61b5c0718f7f0,dropped_off_at,2016-06-13 10:03:05,2016-06-13 10:03:05,2016,6,13,10:03:05,10,3,5
5,00005eae40882760d675da5effb89ae3,requested_at,2016-05-14 05:23:21,2016-05-14 05:23:21,2016,5,14,05:23:21,5,23,21
6,00005eae40882760d675da5effb89ae3,accepted_at,2016-05-14 05:23:25,2016-05-14 05:23:25,2016,5,14,05:23:25,5,23,25
7,00005eae40882760d675da5effb89ae3,arrived_at,2016-05-14 05:26:17,2016-05-14 05:26:17,2016,5,14,05:26:17,5,26,17
8,00005eae40882760d675da5effb89ae3,picked_up_at,2016-05-14 05:26:18,2016-05-14 05:26:18,2016,5,14,05:26:18,5,26,18
9,00005eae40882760d675da5effb89ae3,dropped_off_at,2016-05-14 05:34:17,2016-05-14 05:34:17,2016,5,14,05:34:17,5,34,17
10,000061d42cf29f73b591041d9a1b2973,requested_at,2016-05-16 15:43:09,2016-05-16 15:43:09,2016,5,16,15:43:09,15,43,9
11,000061d42cf29f73b591041d9a1b2973,accepted_at,2016-05-16 15:43:14,2016-05-16 15:43:14,2016,5,16,15:43:14,15,43,14
12,000061d42cf29f73b591041d9a1b2973,arrived_at,2016-05-16 15:47:29,2016-05-16 15:47:29,2016,5,16,15:47:29,15,47,29
13,000061d42cf29f73b591041d9a1b2973,picked_up_at,2016-05-16 15:47:32,2016-05-16 15:47:32,2016,5,16,15:47:32,15,47,32
14,000061d42cf29f73b591041d9a1b2973,dropped_off_at,2016-05-16 15:54:18,2016-05-16 15:54:18,2016,5,16,15:54:18,15,54,18
15,00006efeb0d5e3ccad7d921ddeee9900,requested_at,2016-05-11 19:29:36,2016-05-11 19:29:36,2016,5,11,19:29:36,19,29,36
16,00006efeb0d5e3ccad7d921ddeee9900,accepted_at,2016-05-11 19:29:43,2016-05-11 19:29:43,2016,5,11,19:29:43,19,29,43
17,00006efeb0d5e3ccad7d921ddeee9900,arrived_at,2016-05-11 19:35:11,2016-05-11 19:35:11,2016,5,11,19:35:11,19,35,11
18,00006efeb0d5e3ccad7d921ddeee9900,picked_up_at,2016-05-11 19:35:15,2016-05-11 19:35:15,2016,5,11,19:35:15,19,35,15
19,00006efeb0d5e3ccad7d921ddeee9900,dropped_off_at,2016-05-11 19:40:47,2016-05-11 19:40:47,2016,5,11,19:40:47,19,40,47
20,0000d9b24d8ccdd991b76258e616fa01,requested_at,2016-04-26 18:11:38,2016-04-26 18:11:38,2016,4,26,18:11:38,18,11,38
21,0000d9b24d8ccdd991b76258e616fa01,accepted_at,2016-04-26 18:12:15,2016-04-26 18:12:15,2016,4,26,18:12:15,18,12,15
22,0000d9b24d8ccdd991b76258e616fa01,arrived_at,2016-04-26 18:16:52,2016-04-26 18:16:52,2016,4,26,18:16:52,18,16,52
23,0000d9b24d8ccdd991b76258e616fa01,picked_up_at,2016-04-26 18:16:55,2016-04-26 18:16:55,2016,4,26,18:16:55,18,16,55
24,0000d9b24d8ccdd991b76258e616fa01,dropped_off_at,2016-04-26 18:24:14,2016-04-26 18:24:14,2016,4,26,18:24:14,18,24,14
25,00012759befd5d34a0609800f6a1ee59,requested_at,2016-05-31 15:44:56,2016-05-31 15:44:56,2016,5,31,15:44:56,15,44,56
26,00012759befd5d34a0609800f6a1ee59,accepted_at,2016-05-31 15:45:05,2016-05-31 15:45:05,2016,5,31,15:45:05,15,45,5
27,00012759befd5d34a0609800f6a1ee59,arrived_at,2016-05-31 15:46:22,2016-05-31 15:46:22,2016,5,31,15:46:22,15,46,22
28,00012759befd5d34a0609800f6a1ee59,picked_up_at,2016-05-31 15:46:23,2016-05-31 15:46:23,2016,5,31,15:46:23,15,46,23
29,00012759befd5d34a0609800f6a1ee59,dropped_off_at,2016-05-31 15:59:26,2016-05-31 15:59:26,2016,5,31,15:59:26,15,59,26
...,...,...,...,...,...,...,...,...,...,...,...
970375,fffe942c46a5b2039fa01ba4c3d390e8,requested_at,2016-05-17 19:56:09,2016-05-17 19:56:09,2016,5,17,19:56:09,19,56,9
970376,fffe942c46a5b2039fa01ba4c3d390e8,accepted_at,2016-05-17 19:56:13,2016-05-17 19:56:13,2016,5,17,19:56:13,19,56,13
970377,fffe942c46a5b2039fa01ba4c3d390e8,arrived_at,2016-05-17 19:58:50,2016-05-17 19:58:50,2016,5,17,19:58:50,19,58,50
970378,fffe942c46a5b2039fa01ba4c3d390e8,picked_up_at,2016-05-17 19:58:52,2016-05-17 19:58:52,2016,5,17,19:58:52,19,58,52
970379,fffe942c46a5b2039fa01ba4c3d390e8,dropped_off_at,2016-05-17 20:11:11,2016-05-17 20:11:11,2016,5,17,20:11:11,20,11,11
970380,fffebb46effb90ce758fdff68b569355,requested_at,2016-06-16 09:57:07,2016-06-16 09:57:07,2016,6,16,09:57:07,9,57,7
970381,fffebb46effb90ce758fdff68b569355,accepted_at,2016-06-16 09:57:12,2016-06-16 09:57:12,2016,6,16,09:57:12,9,57,12
970382,fffebb46effb90ce758fdff68b569355,arrived_at,2016-06-16 09:58:54,2016-06-16 09:58:54,2016,6,16,09:58:54,9,58,54
970383,fffebb46effb90ce758fdff68b569355,picked_up_at,2016-06-16 09:58:57,2016-06-16 09:58:57,2016,6,16,09:58:57,9,58,57
970384,fffebb46effb90ce758fdff68b569355,dropped_off_at,2016-06-16 10:15:08,2016-06-16 10:15:08,2016,6,16,10:15:08,10,15,8
970385,ffff9c38173ddfa17bdd115c463e329f,requested_at,2016-06-03 18:34:00,2016-06-03 18:34:00,2016,6,3,18:34:00,18,34,0
970386,ffff9c38173ddfa17bdd115c463e329f,accepted_at,2016-06-03 18:34:07,2016-06-03 18:34:07,2016,6,3,18:34:07,18,34,7
970387,ffff9c38173ddfa17bdd115c463e329f,arrived_at,2016-06-03 18:35:20,2016-06-03 18:35:20,2016,6,3,18:35:20,18,35,20
970388,ffff9c38173ddfa17bdd115c463e329f,picked_up_at,2016-06-03 18:35:22,2016-06-03 18:35:22,2016,6,3,18:35:22,18,35,22
970389,ffff9c38173ddfa17bdd115c463e329f,dropped_off_at,2016-06-03 18:50:08,2016-06-03 18:50:08,2016,6,3,18:50:08,18,50,8
970390,ffff9e431f7fade54b2550ac19ab6e64,requested_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10
970391,ffff9e431f7fade54b2550ac19ab6e64,accepted_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10
970392,ffff9e431f7fade54b2550ac19ab6e64,arrived_at,2016-06-12 04:04:35,2016-06-12 04:04:35,2016,6,12,04:04:35,4,4,35
970393,ffff9e431f7fade54b2550ac19ab6e64,picked_up_at,2016-06-12 04:04:37,2016-06-12 04:04:37,2016,6,12,04:04:37,4,4,37
970394,ffff9e431f7fade54b2550ac19ab6e64,dropped_off_at,2016-06-12 04:15:42,2016-06-12 04:15:42,2016,6,12,04:15:42,4,15,42
970395,ffffa07f48f2f885f714765d794ad596,requested_at,2016-04-19 01:08:57,2016-04-19 01:08:57,2016,4,19,01:08:57,1,8,57
970396,ffffa07f48f2f885f714765d794ad596,accepted_at,2016-04-19 01:09:12,2016-04-19 01:09:12,2016,4,19,01:09:12,1,9,12
970397,ffffa07f48f2f885f714765d794ad596,arrived_at,2016-04-19 01:10:49,2016-04-19 01:10:49,2016,4,19,01:10:49,1,10,49
970398,ffffa07f48f2f885f714765d794ad596,picked_up_at,2016-04-19 01:10:50,2016-04-19 01:10:50,2016,4,19,01:10:50,1,10,50
970399,ffffa07f48f2f885f714765d794ad596,dropped_off_at,2016-04-19 01:30:48,2016-04-19 01:30:48,2016,4,19,01:30:48,1,30,48
970400,ffffccd77f47a3de26dfed9a851464b4,requested_at,2016-05-18 08:44:13,2016-05-18 08:44:13,2016,5,18,08:44:13,8,44,13
970401,ffffccd77f47a3de26dfed9a851464b4,accepted_at,2016-05-18 08:44:21,2016-05-18 08:44:21,2016,5,18,08:44:21,8,44,21
970402,ffffccd77f47a3de26dfed9a851464b4,arrived_at,2016-05-18 08:44:36,2016-05-18 08:44:36,2016,5,18,08:44:36,8,44,36
970403,ffffccd77f47a3de26dfed9a851464b4,picked_up_at,2016-05-18 08:44:42,2016-05-18 08:44:42,2016,5,18,08:44:42,8,44,42
970404,ffffccd77f47a3de26dfed9a851464b4,dropped_off_at,2016-05-18 09:11:37,2016-05-18 09:11:37,2016,5,18,09:11:37,9,11,37

In [205]:
# create a new column that will hold the time it takes for a driver 
# to arrive to set destination
ride_timestamps_df["wait_num"] = 0

,ride_id,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds,wait_num
0,00003037a262d9ee40e61b5c0718f7f0,requested_at,2016-06-13 09:39:19,2016-06-13 09:39:19,2016,6,13,09:39:19,9,39,19,0
1,00003037a262d9ee40e61b5c0718f7f0,accepted_at,2016-06-13 09:39:51,2016-06-13 09:39:51,2016,6,13,09:39:51,9,39,51,0
2,00003037a262d9ee40e61b5c0718f7f0,arrived_at,2016-06-13 09:44:31,2016-06-13 09:44:31,2016,6,13,09:44:31,9,44,31,0
3,00003037a262d9ee40e61b5c0718f7f0,picked_up_at,2016-06-13 09:44:33,2016-06-13 09:44:33,2016,6,13,09:44:33,9,44,33,0
4,00003037a262d9ee40e61b5c0718f7f0,dropped_off_at,2016-06-13 10:03:05,2016-06-13 10:03:05,2016,6,13,10:03:05,10,3,5,0
5,00005eae40882760d675da5effb89ae3,requested_at,2016-05-14 05:23:21,2016-05-14 05:23:21,2016,5,14,05:23:21,5,23,21,0
6,00005eae40882760d675da5effb89ae3,accepted_at,2016-05-14 05:23:25,2016-05-14 05:23:25,2016,5,14,05:23:25,5,23,25,0
7,00005eae40882760d675da5effb89ae3,arrived_at,2016-05-14 05:26:17,2016-05-14 05:26:17,2016,5,14,05:26:17,5,26,17,0
8,00005eae40882760d675da5effb89ae3,picked_up_at,2016-05-14 05:26:18,2016-05-14 05:26:18,2016,5,14,05:26:18,5,26,18,0
9,00005eae40882760d675da5effb89ae3,dropped_off_at,2016-05-14 05:34:17,2016-05-14 05:34:17,2016,5,14,05:34:17,5,34,17,0
10,000061d42cf29f73b591041d9a1b2973,requested_at,2016-05-16 15:43:09,2016-05-16 15:43:09,2016,5,16,15:43:09,15,43,9,0
11,000061d42cf29f73b591041d9a1b2973,accepted_at,2016-05-16 15:43:14,2016-05-16 15:43:14,2016,5,16,15:43:14,15,43,14,0
12,000061d42cf29f73b591041d9a1b2973,arrived_at,2016-05-16 15:47:29,2016-05-16 15:47:29,2016,5,16,15:47:29,15,47,29,0
13,000061d42cf29f73b591041d9a1b2973,picked_up_at,2016-05-16 15:47:32,2016-05-16 15:47:32,2016,5,16,15:47:32,15,47,32,0
14,000061d42cf29f73b591041d9a1b2973,dropped_off_at,2016-05-16 15:54:18,2016-05-16 15:54:18,2016,5,16,15:54:18,15,54,18,0
15,00006efeb0d5e3ccad7d921ddeee9900,requested_at,2016-05-11 19:29:36,2016-05-11 19:29:36,2016,5,11,19:29:36,19,29,36,0
16,00006efeb0d5e3ccad7d921ddeee9900,accepted_at,2016-05-11 19:29:43,2016-05-11 19:29:43,2016,5,11,19:29:43,19,29,43,0
17,00006efeb0d5e3ccad7d921ddeee9900,arrived_at,2016-05-11 19:35:11,2016-05-11 19:35:11,2016,5,11,19:35:11,19,35,11,0
18,00006efeb0d5e3ccad7d921ddeee9900,picked_up_at,2016-05-11 19:35:15,2016-05-11 19:35:15,2016,5,11,19:35:15,19,35,15,0
19,00006efeb0d5e3ccad7d921ddeee9900,dropped_off_at,2016-05-11 19:40:47,2016-05-11 19:40:47,2016,5,11,19:40:47,19,40,47,0
20,0000d9b24d8ccdd991b76258e616fa01,requested_at,2016-04-26 18:11:38,2016-04-26 18:11:38,2016,4,26,18:11:38,18,11,38,0
21,0000d9b24d8ccdd991b76258e616fa01,accepted_at,2016-04-26 18:12:15,2016-04-26 18:12:15,2016,4,26,18:12:15,18,12,15,0
22,0000d9b24d8ccdd991b76258e616fa01,arrived_at,2016-04-26 18:16:52,2016-04-26 18:16:52,2016,4,26,18:16:52,18,16,52,0
23,0000d9b24d8ccdd991b76258e616fa01,picked_up_at,2016-04-26 18:16:55,2016-04-26 18:16:55,2016,4,26,18:16:55,18,16,55,0
24,0000d9b24d8ccdd991b76258e616fa01,dropped_off_at,2016-04-26 18:24:14,2016-04-26 18:24:14,2016,4,26,18:24:14,18,24,14,0
25,00012759befd5d34a0609800f6a1ee59,requested_at,2016-05-31 15:44:56,2016-05-31 15:44:56,2016,5,31,15:44:56,15,44,56,0
26,00012759befd5d34a0609800f6a1ee59,accepted_at,2016-05-31 15:45:05,2016-05-31 15:45:05,2016,5,31,15:45:05,15,45,5,0
27,00012759befd5d34a0609800f6a1ee59,arrived_at,2016-05-31 15:46:22,2016-05-31 15:46:22,2016,5,31,15:46:22,15,46,22,0
28,00012759befd5d34a0609800f6a1ee59,picked_up_at,2016-05-31 15:46:23,2016-05-31 15:46:23,2016,5,31,15:46:23,15,46,23,0
29,00012759befd5d34a0609800f6a1ee59,dropped_off_at,2016-05-31 15:59:26,2016-05-31 15:59:26,2016,5,31,15:59:26,15,59,26,0
...,...,...,...,...,...,...,...,...,...,...,...,...
970375,fffe942c46a5b2039fa01ba4c3d390e8,requested_at,2016-05-17 19:56:09,2016-05-17 19:56:09,2016,5,17,19:56:09,19,56,9,0
970376,fffe942c46a5b2039fa01ba4c3d390e8,accepted_at,2016-05-17 19:56:13,2016-05-17 19:56:13,2016,5,17,19:56:13,19,56,13,0
970377,fffe942c46a5b2039fa01ba4c3d390e8,arrived_at,2016-05-17 19:58:50,2016-05-17 19:58:50,2016,5,17,19:58:50,19,58,50,0
970378,fffe942c46a5b2039fa01ba4c3d390e8,picked_up_at,2016-05-17 19:58:52,2016-05-17 19:58:52,2016,5,17,19:58:52,19,58,52,0
970379,fffe942c46a5b2039fa01ba4c3d390e8,dropped_off_at,2016-05-17 20:11:11,2016-05-17 20:11:11,2016,5,17,20:11:11,20,11,11,0
970380,fffebb46effb90ce758fdff68b569355,requested_at,2016-06-16 09:57:07,2016-06-16 09:57:07,2016,6,16,09:57:07,9,57,7,0
970381,fffebb46effb90ce758fdff68b569355,accepted_at,2016-06-16 09:57:12,2016-06-16 09:57:12,2016,6,16,09:57:12,9,57,12,0
970382,fffebb46effb90ce758fdff68b569355,arrived_at,2016-06-16 09:58:54,2016-06-16 09:58:54,2016,6,16,09:58:54,9,58,54,0
970383,fffebb46effb90ce758fdff68b569355,picked_up_at,2016-06-16 09:58:57,2016-06-16 09:58:57,2016,6,16,09:58:57,9,58,57,0
970384,fffebb46effb90ce758fdff68b569355,dropped_off_at,2016-06-16 10:15:08,2016-06-16 10:15:08,2016,6,16,10:15:08,10,15,8,0
970385,ffff9c38173ddfa17bdd115c463e329f,requested_at,2016-06-03 18:34:00,2016-06-03 18:34:00,2016,6,3,18:34:00,18,34,0,0
970386,ffff9c38173ddfa17bdd115c463e329f,accepted_at,2016-06-03 18:34:07,2016-06-03 18:34:07,2016,6,3,18:34:07,18,34,7,0
970387,ffff9c38173ddfa17bdd115c463e329f,arrived_at,2016-06-03 18:35:20,2016-06-03 18:35:20,2016,6,3,18:35:20,18,35,20,0
970388,ffff9c38173ddfa17bdd115c463e329f,picked_up_at,2016-06-03 18:35:22,2016-06-03 18:35:22,2016,6,3,18:35:22,18,35,22,0
970389,ffff9c38173ddfa17bdd115c463e329f,dropped_off_at,2016-06-03 18:50:08,2016-06-03 18:50:08,2016,6,3,18:50:08,18,50,8,0
970390,ffff9e431f7fade54b2550ac19ab6e64,requested_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10,0
970391,ffff9e431f7fade54b2550ac19ab6e64,accepted_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10,0
970392,ffff9e431f7fade54b2550ac19ab6e64,arrived_at,2016-06-12 04:04:35,2016-06-12 04:04:35,2016,6,12,04:04:35,4,4,35,0
970393,ffff9e431f7fade54b2550ac19ab6e64,picked_up_at,2016-06-12 04:04:37,2016-06-12 04:04:37,2016,6,12,04:04:37,4,4,37,0
970394,ffff9e431f7fade54b2550ac19ab6e64,dropped_off_at,2016-06-12 04:15:42,2016-06-12 04:15:42,2016,6,12,04:15:42,4,15,42,0
970395,ffffa07f48f2f885f714765d794ad596,requested_at,2016-04-19 01:08:57,2016-04-19 01:08:57,2016,4,19,01:08:57,1,8,57,0
970396,ffffa07f48f2f885f714765d794ad596,accepted_at,2016-04-19 01:09:12,2016-04-19 01:09:12,2016,4,19,01:09:12,1,9,12,0
970397,ffffa07f48f2f885f714765d794ad596,arrived_at,2016-04-19 01:10:49,2016-04-19 01:10:49,2016,4,19,01:10:49,1,10,49,0
970398,ffffa07f48f2f885f714765d794ad596,picked_up_at,2016-04-19 01:10:50,2016-04-19 01:10:50,2016,4,19,01:10:50,1,10,50,0
970399,ffffa07f48f2f885f714765d794ad596,dropped_off_at,2016-04-19 01:30:48,2016-04-19 01:30:48,2016,4,19,01:30:48,1,30,48,0
970400,ffffccd77f47a3de26dfed9a851464b4,requested_at,2016-05-18 08:44:13,2016-05-18 08:44:13,2016,5,18,08:44:13,8,44,13,0
970401,ffffccd77f47a3de26dfed9a851464b4,accepted_at,2016-05-18 08:44:21,2016-05-18 08:44:21,2016,5,18,08:44:21,8,44,21,0
970402,ffffccd77f47a3de26dfed9a851464b4,arrived_at,2016-05-18 08:44:36,2016-05-18 08:44:36,2016,5,18,08:44:36,8,44,36,0
970403,ffffccd77f47a3de26dfed9a851464b4,picked_up_at,2016-05-18 08:44:42,2016-05-18 08:44:42,2016,5,18,08:44:42,8,44,42,0
970404,ffffccd77f47a3de26dfed9a851464b4,dropped_off_at,2016-05-18 09:11:37,2016-05-18 09:11:37,2016,5,18,09:11:37,9,11,37,0

creates a table of arrivals and a table of requests

resets the index of the requests and sorts the values

In [206]:
table_arrived_at = pd.DataFrame(ride_timestamps_df.loc[ride_timestamps_df['event'] == "accepted_at"])
table_requested_at = pd.DataFrame(ride_timestamps_df.loc[ride_timestamps_df['event'] == "requested_at"])

table_arrived_at = table_arrived_at.reset_index()
table_requested_at = table_requested_at.reset_index()

table_arrived_at = table_arrived_at.drop(['index'], axis = 1)
table_requested_at = table_requested_at.drop(['index'], axis = 1)

# table_requested_at["wait_num"] = -1 * table_requested_at["wait_num"]
table_arrived_at = table_arrived_at.sort_values("ride_id", ascending=True)
table_requested_at = table_requested_at.sort_values("ride_id", ascending=True)

both_tables = pd.concat([table_arrived_at, table_requested_at], ignore_index=True)
both_tables.sort_values("ride_id")

,ride_id,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds,wait_num
0,00003037a262d9ee40e61b5c0718f7f0,accepted_at,2016-06-13 09:39:51,2016-06-13 09:39:51,2016,6,13,09:39:51,9,39,51,0
194080,00003037a262d9ee40e61b5c0718f7f0,requested_at,2016-06-13 09:39:19,2016-06-13 09:39:19,2016,6,13,09:39:19,9,39,19,0
194081,00005eae40882760d675da5effb89ae3,requested_at,2016-05-14 05:23:21,2016-05-14 05:23:21,2016,5,14,05:23:21,5,23,21,0
1,00005eae40882760d675da5effb89ae3,accepted_at,2016-05-14 05:23:25,2016-05-14 05:23:25,2016,5,14,05:23:25,5,23,25,0
2,000061d42cf29f73b591041d9a1b2973,accepted_at,2016-05-16 15:43:14,2016-05-16 15:43:14,2016,5,16,15:43:14,15,43,14,0
194082,000061d42cf29f73b591041d9a1b2973,requested_at,2016-05-16 15:43:09,2016-05-16 15:43:09,2016,5,16,15:43:09,15,43,9,0
3,00006efeb0d5e3ccad7d921ddeee9900,accepted_at,2016-05-11 19:29:43,2016-05-11 19:29:43,2016,5,11,19:29:43,19,29,43,0
194083,00006efeb0d5e3ccad7d921ddeee9900,requested_at,2016-05-11 19:29:36,2016-05-11 19:29:36,2016,5,11,19:29:36,19,29,36,0
4,0000d9b24d8ccdd991b76258e616fa01,accepted_at,2016-04-26 18:12:15,2016-04-26 18:12:15,2016,4,26,18:12:15,18,12,15,0
194084,0000d9b24d8ccdd991b76258e616fa01,requested_at,2016-04-26 18:11:38,2016-04-26 18:11:38,2016,4,26,18:11:38,18,11,38,0
194085,00012759befd5d34a0609800f6a1ee59,requested_at,2016-05-31 15:44:56,2016-05-31 15:44:56,2016,5,31,15:44:56,15,44,56,0
5,00012759befd5d34a0609800f6a1ee59,accepted_at,2016-05-31 15:45:05,2016-05-31 15:45:05,2016,5,31,15:45:05,15,45,5,0
194086,0001480a2c27492b1f8cb5fbc38ca667,requested_at,2016-06-05 01:58:44,2016-06-05 01:58:44,2016,6,5,01:58:44,1,58,44,0
6,0001480a2c27492b1f8cb5fbc38ca667,accepted_at,2016-06-05 01:58:52,2016-06-05 01:58:52,2016,6,5,01:58:52,1,58,52,0
194087,0002033cf1878734f3ffec9ad9748b3e,requested_at,2016-05-28 21:03:45,2016-05-28 21:03:45,2016,5,28,21:03:45,21,3,45,0
7,0002033cf1878734f3ffec9ad9748b3e,accepted_at,2016-05-28 21:03:52,2016-05-28 21:03:52,2016,5,28,21:03:52,21,3,52,0
194088,0002090d41c4050b1683e3c4f69ed1c4,requested_at,2016-06-23 16:12:31,2016-06-23 16:12:31,2016,6,23,16:12:31,16,12,31,0
8,0002090d41c4050b1683e3c4f69ed1c4,accepted_at,2016-06-23 16:12:37,2016-06-23 16:12:37,2016,6,23,16:12:37,16,12,37,0
194089,00024c06e3554012303d4caa449222f3,requested_at,2016-06-19 01:55:52,2016-06-19 01:55:52,2016,6,19,01:55:52,1,55,52,0
9,00024c06e3554012303d4caa449222f3,accepted_at,2016-06-19 01:55:58,2016-06-19 01:55:58,2016,6,19,01:55:58,1,55,58,0
194090,000290b418595bfe228d2bf4d4e331df,requested_at,2016-04-30 23:30:19,2016-04-30 23:30:19,2016,4,30,23:30:19,23,30,19,0
10,000290b418595bfe228d2bf4d4e331df,accepted_at,2016-04-30 23:30:22,2016-04-30 23:30:22,2016,4,30,23:30:22,23,30,22,0
194091,0002928349cb115e78e5a9e172f987f3,requested_at,2016-06-10 03:38:31,2016-06-10 03:38:31,2016,6,10,03:38:31,3,38,31,0
11,0002928349cb115e78e5a9e172f987f3,accepted_at,2016-06-10 03:38:37,2016-06-10 03:38:37,2016,6,10,03:38:37,3,38,37,0
12,00029ca867a194935a134297165152fc,accepted_at,2016-06-13 08:25:31,2016-06-13 08:25:31,2016,6,13,08:25:31,8,25,31,0
194092,00029ca867a194935a134297165152fc,requested_at,2016-06-13 08:25:24,2016-06-13 08:25:24,2016,6,13,08:25:24,8,25,24,0
13,0002c4eccf2dac74132506de8087261e,accepted_at,2016-06-21 20:40:42,2016-06-21 20:40:42,2016,6,21,20:40:42,20,40,42,0
194093,0002c4eccf2dac74132506de8087261e,requested_at,2016-06-21 20:40:36,2016-06-21 20:40:36,2016,6,21,20:40:36,20,40,36,0
14,0002c71a866c07b68b5ff8cdfd003ea0,accepted_at,2016-05-30 19:47:38,2016-05-30 19:47:38,2016,5,30,19:47:38,19,47,38,0
194094,0002c71a866c07b68b5ff8cdfd003ea0,requested_at,2016-05-30 19:47:11,2016-05-30 19:47:11,2016,5,30,19:47:11,19,47,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...
388145,fffa6e36c119735b739307ec15b52a04,requested_at,2016-05-05 21:30:58,2016-05-05 21:30:58,2016,5,5,21:30:58,21,30,58,0
194065,fffa6e36c119735b739307ec15b52a04,accepted_at,2016-05-05 21:31:03,2016-05-05 21:31:03,2016,5,5,21:31:03,21,31,3,0
194066,fffab94b777130200293f7233faa80f7,accepted_at,2016-04-29 09:55:12,2016-04-29 09:55:12,2016,4,29,09:55:12,9,55,12,0
388146,fffab94b777130200293f7233faa80f7,requested_at,2016-04-29 09:55:03,2016-04-29 09:55:03,2016,4,29,09:55:03,9,55,3,0
388147,fffad62798420b83b5f179edc4260dd2,requested_at,2016-06-23 14:40:34,2016-06-23 14:40:34,2016,6,23,14:40:34,14,40,34,0
194067,fffad62798420b83b5f179edc4260dd2,accepted_at,2016-06-23 14:40:40,2016-06-23 14:40:40,2016,6,23,14:40:40,14,40,40,0
388148,fffbdc0bbb975217401bdd24d66a3ac9,requested_at,2016-05-29 21:54:13,2016-05-29 21:54:13,2016,5,29,21:54:13,21,54,13,0
194068,fffbdc0bbb975217401bdd24d66a3ac9,accepted_at,2016-05-29 21:54:52,2016-05-29 21:54:52,2016,5,29,21:54:52,21,54,52,0
388149,fffcf368d05983e45d910d714ac80819,requested_at,2016-06-23 08:14:20,2016-06-23 08:14:20,2016,6,23,08:14:20,8,14,20,0
194069,fffcf368d05983e45d910d714ac80819,accepted_at,2016-06-23 08:14:30,2016-06-23 08:14:30,2016,6,23,08:14:30,8,14,30,0
388150,fffd6c6bdfb2ecafe031797a5afba4a0,requested_at,2016-06-24 09:00:21,2016-06-24 09:00:21,2016,6,24,09:00:21,9,0,21,0
194070,fffd6c6bdfb2ecafe031797a5afba4a0,accepted_at,2016-06-24 09:00:26,2016-06-24 09:00:26,2016,6,24,09:00:26,9,0,26,0
388151,fffd9426f1c055691ae1ab2e013aa4b8,requested_at,2016-06-25 00:50:11,2016-06-25 00:50:11,2016,6,25,00:50:11,0,50,11,0
194071,fffd9426f1c055691ae1ab2e013aa4b8,accepted_at,2016-06-25 00:50:18,2016-06-25 00:50:18,2016,6,25,00:50:18,0,50,18,0
388152,fffe21d101e8c85fbf94b05bdb24c951,requested_at,2016-06-09 08:24:42,2016-06-09 08:24:42,2016,6,9,08:24:42,8,24,42,0
194072,fffe21d101e8c85fbf94b05bdb24c951,accepted_at,2016-06-09 08:24:59,2016-06-09 08:24:59,2016,6,9,08:24:59,8,24,59,0
388153,fffe87c305afa41349e56f63731e04ea,requested_at,2016-05-04 22:02:24,2016-05-04 22:02:24,2016,5,4,22:02:24,22,2,24,0
194073,fffe87c305afa41349e56f63731e04ea,accepted_at,2016-05-04 22:02:34,2016-05-04 22:02:34,2016,5,4,22:02:34,22,2,34,0
194074,fffe942c46a5b2039fa01ba4c3d390e8,accepted_at,2016-05-17 19:56:13,2016-05-17 19:56:13,2016,5,17,19:56:13,19,56,13,0
388154,fffe942c46a5b2039fa01ba4c3d390e8,requested_at,2016-05-17 19:56:09,2016-05-17 19:56:09,2016,5,17,19:56:09,19,56,9,0
388155,fffebb46effb90ce758fdff68b569355,requested_at,2016-06-16 09:57:07,2016-06-16 09:57:07,2016,6,16,09:57:07,9,57,7,0
194075,fffebb46effb90ce758fdff68b569355,accepted_at,2016-06-16 09:57:12,2016-06-16 09:57:12,2016,6,16,09:57:12,9,57,12,0
388156,ffff9c38173ddfa17bdd115c463e329f,requested_at,2016-06-03 18:34:00,2016-06-03 18:34:00,2016,6,3,18:34:00,18,34,0,0
194076,ffff9c38173ddfa17bdd115c463e329f,accepted_at,2016-06-03 18:34:07,2016-06-03 18:34:07,2016,6,3,18:34:07,18,34,7,0
388157,ffff9e431f7fade54b2550ac19ab6e64,requested_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10,0
194077,ffff9e431f7fade54b2550ac19ab6e64,accepted_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10,0
388158,ffffa07f48f2f885f714765d794ad596,requested_at,2016-04-19 01:08:57,2016-04-19 01:08:57,2016,4,19,01:08:57,1,8,57,0
194078,ffffa07f48f2f885f714765d794ad596,accepted_at,2016-04-19 01:09:12,2016-04-19 01:09:12,2016,4,19,01:09:12,1,9,12,0
194079,ffffccd77f47a3de26dfed9a851464b4,accepted_at,2016-05-18 08:44:21,2016-05-18 08:44:21,2016,5,18,08:44:21,8,44,21,0
388159,ffffccd77f47a3de26dfed9a851464b4,requested_at,2016-05-18 08:44:13,2016-05-18 08:44:13,2016,5,18,08:44:13,8,44,13,0

In [209]:

for i in range(194080): 
    myhour = 0
    my_minute = 0
    
    if table_requested_at["Seconds"][i] > table_arrived_at["Seconds"][i]:
        table_arrived_at["Minutes"][i] -= 1
        table_arrived_at["Seconds"][i] += 60
    myminute = abs(table_arrived_at["Minutes"][i] - table_requested_at["Minutes"][i]) 
    myhour = abs(table_requested_at["Seconds"][i] - table_arrived_at["Seconds"][i])
    total_time = myminute*60 + myhour
    table_arrived_at.loc[table_arrived_at.index == i, "wait_num"] = total_time

table_arrived_at

,ride_id,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds,wait_num
0,00003037a262d9ee40e61b5c0718f7f0,accepted_at,2016-06-13 09:39:51,2016-06-13 09:39:51,2016,6,13,09:39:51,9,39,51,32
1,00005eae40882760d675da5effb89ae3,accepted_at,2016-05-14 05:23:25,2016-05-14 05:23:25,2016,5,14,05:23:25,5,23,25,4
2,000061d42cf29f73b591041d9a1b2973,accepted_at,2016-05-16 15:43:14,2016-05-16 15:43:14,2016,5,16,15:43:14,15,43,14,5
3,00006efeb0d5e3ccad7d921ddeee9900,accepted_at,2016-05-11 19:29:43,2016-05-11 19:29:43,2016,5,11,19:29:43,19,29,43,7
4,0000d9b24d8ccdd991b76258e616fa01,accepted_at,2016-04-26 18:12:15,2016-04-26 18:12:15,2016,4,26,18:12:15,18,11,75,37
5,00012759befd5d34a0609800f6a1ee59,accepted_at,2016-05-31 15:45:05,2016-05-31 15:45:05,2016,5,31,15:45:05,15,44,65,9
6,0001480a2c27492b1f8cb5fbc38ca667,accepted_at,2016-06-05 01:58:52,2016-06-05 01:58:52,2016,6,5,01:58:52,1,58,52,8
7,0002033cf1878734f3ffec9ad9748b3e,accepted_at,2016-05-28 21:03:52,2016-05-28 21:03:52,2016,5,28,21:03:52,21,3,52,7
8,0002090d41c4050b1683e3c4f69ed1c4,accepted_at,2016-06-23 16:12:37,2016-06-23 16:12:37,2016,6,23,16:12:37,16,12,37,6
9,00024c06e3554012303d4caa449222f3,accepted_at,2016-06-19 01:55:58,2016-06-19 01:55:58,2016,6,19,01:55:58,1,55,58,6
10,000290b418595bfe228d2bf4d4e331df,accepted_at,2016-04-30 23:30:22,2016-04-30 23:30:22,2016,4,30,23:30:22,23,30,22,3
11,0002928349cb115e78e5a9e172f987f3,accepted_at,2016-06-10 03:38:37,2016-06-10 03:38:37,2016,6,10,03:38:37,3,38,37,6
12,00029ca867a194935a134297165152fc,accepted_at,2016-06-13 08:25:31,2016-06-13 08:25:31,2016,6,13,08:25:31,8,25,31,7
13,0002c4eccf2dac74132506de8087261e,accepted_at,2016-06-21 20:40:42,2016-06-21 20:40:42,2016,6,21,20:40:42,20,40,42,6
14,0002c71a866c07b68b5ff8cdfd003ea0,accepted_at,2016-05-30 19:47:38,2016-05-30 19:47:38,2016,5,30,19:47:38,19,47,38,27
15,000399d2e73490f5ac5e65eae391f6f8,accepted_at,2016-06-25 19:55:54,2016-06-25 19:55:54,2016,6,25,19:55:54,19,55,54,7
16,0003bd8128cced32fcb88aa3805b0a72,accepted_at,2016-04-26 21:21:26,2016-04-26 21:21:26,2016,4,26,21:21:26,21,21,26,5
17,000422a0d02abcf059a579d1cd60bdc9,accepted_at,2016-06-14 22:44:05,2016-06-14 22:44:05,2016,6,14,22:44:05,22,44,5,5
18,00046fb60349e54c9845d667d7c897fd,accepted_at,2016-05-08 01:59:25,2016-05-08 01:59:25,2016,5,8,01:59:25,1,59,25,5
19,0004a3db0fb83d99007c394173660ac3,accepted_at,2016-05-27 01:19:14,2016-05-27 01:19:14,2016,5,27,01:19:14,1,19,14,73
20,0004b5e8b5df564779e20ce317f68c48,accepted_at,2016-05-07 22:42:50,2016-05-07 22:42:50,2016,5,7,22:42:50,22,42,50,10
21,0004d0b38d8b264cab0f03e34c2f52d3,accepted_at,2016-05-27 23:10:21,2016-05-27 23:10:21,2016,5,27,23:10:21,23,9,81,29
22,000527ec3aa73cc922d8a4858edf9c06,accepted_at,2016-04-13 22:55:11,2016-04-13 22:55:11,2016,4,13,22:55:11,22,55,11,6
23,00053e4ae1b3bfe921b3b499e4dc9ab3,accepted_at,2016-06-14 22:24:39,2016-06-14 22:24:39,2016,6,14,22:24:39,22,24,39,4
24,00058997f105bbd89b57fe0df10095c1,accepted_at,2016-05-25 23:25:06,2016-05-25 23:25:06,2016,5,25,23:25:06,23,25,6,5
25,00062b47908be1bf23ce194c0feca420,accepted_at,2016-06-14 15:59:45,2016-06-14 15:59:45,2016,6,14,15:59:45,15,59,45,4
26,00070d6d3eb01e6444b7da3a68846507,accepted_at,2016-06-14 07:33:28,2016-06-14 07:33:28,2016,6,14,07:33:28,7,33,28,4
27,0007f92b090f91c4041c94bc2d6786e2,accepted_at,2016-06-12 19:51:34,2016-06-12 19:51:34,2016,6,12,19:51:34,19,51,34,3
28,0008072782166aada78a9da47b0e01fd,accepted_at,2016-04-26 12:56:46,2016-04-26 12:56:46,2016,4,26,12:56:46,12,56,46,8
29,00088cf50ace520d5787c3a532f17e84,accepted_at,2016-05-23 12:38:45,2016-05-23 12:38:45,2016,5,23,12:38:45,12,38,45,8
...,...,...,...,...,...,...,...,...,...,...,...,...
194050,fff70949bfcaee69fb8f1558a0282dea,accepted_at,2016-04-29 16:43:59,2016-04-29 16:43:59,2016,4,29,16:43:59,16,43,59,4
194051,fff72f782408c2c894174b7a1e8cfc6e,accepted_at,2016-05-13 11:02:10,2016-05-13 11:02:10,2016,5,13,11:02:10,11,1,70,12
194052,fff78c33c0fd9d4b8d1cc8e59bee4961,accepted_at,2016-05-05 19:23:04,2016-05-05 19:23:04,2016,5,5,19:23:04,19,22,64,10
194053,fff849783a408c12ea4b540fabdb9ab2,accepted_at,2016-05-29 12:14:21,2016-05-29 12:14:21,2016,5,29,12:14:21,12,13,81,37
194054,fff870d2fd515aeaf6f9d2f5c224e613,accepted_at,2016-04-16 21:17:13,2016-04-16 21:17:13,2016,4,16,21:17:13,21,17,13,3
194055,fff876f91b10374effc1c7364d7962bf,accepted_at,2016-05-26 08:55:30,2016-05-26 08:55:30,2016,5,26,08:55:30,8,55,30,4
194056,fff8810affac74edfcdd09499ab4a848,accepted_at,2016-05-18 13:20:16,2016-05-18 13:20:16,2016,5,18,13:20:16,13,20,16,4
194057,fff8c7cca2a343ed675ddd39b742ec38,accepted_at,2016-06-24 20:07:06,2016-06-24 20:07:06,2016,6,24,20:07:06,20,7,6,6
194058,fff90d32189a6b8c37a6e0fb94a10327,accepted_at,2016-06-18 01:10:01,2016-06-18 01:10:01,2016,6,18,01:10:01,1,9,61,6
194059,fff9421eb58b06c24e07cc28bcb5a4ee,accepted_at,2016-05-06 08:30:11,2016-05-06 08:30:11,2016,5,6,08:30:11,8,30,11,7
194060,fff9820c5ed321c9b6cd3f027b37d318,accepted_at,2016-05-24 20:31:00,2016-05-24 20:31:00,2016,5,24,20:31:00,20,30,60,3
194061,fff9866958f16d0d76211b330ef5d772,accepted_at,2016-06-13 09:53:23,2016-06-13 09:53:23,2016,6,13,09:53:23,9,53,23,6
194062,fff9f2a133a87087a48c76eaf21d76fc,accepted_at,2016-05-03 09:19:39,2016-05-03 09:19:39,2016,5,3,09:19:39,9,19,39,8
194063,fffa06c45bc021b13cb6bc3c2679e8e0,accepted_at,2016-06-09 18:45:31,2016-06-09 18:45:31,2016,6,9,18:45:31,18,44,91,37
194064,fffa5815788aa758c8aa3f839860f57e,accepted_at,2016-06-10 21:55:11,2016-06-10 21:55:11,2016,6,10,21:55:11,21,55,11,11
194065,fffa6e36c119735b739307ec15b52a04,accepted_at,2016-05-05 21:31:03,2016-05-05 21:31:03,2016,5,5,21:31:03,21,30,63,5
194066,fffab94b777130200293f7233faa80f7,accepted_at,2016-04-29 09:55:12,2016-04-29 09:55:12,2016,4,29,09:55:12,9,55,12,9
194067,fffad62798420b83b5f179edc4260dd2,accepted_at,2016-06-23 14:40:40,2016-06-23 14:40:40,2016,6,23,14:40:40,14,40,40,6
194068,fffbdc0bbb975217401bdd24d66a3ac9,accepted_at,2016-05-29 21:54:52,2016-05-29 21:54:52,2016,5,29,21:54:52,21,54,52,39
194069,fffcf368d05983e45d910d714ac80819,accepted_at,2016-06-23 08:14:30,2016-06-23 08:14:30,2016,6,23,08:14:30,8,14,30,10
194070,fffd6c6bdfb2ecafe031797a5afba4a0,accepted_at,2016-06-24 09:00:26,2016-06-24 09:00:26,2016,6,24,09:00:26,9,0,26,5
194071,fffd9426f1c055691ae1ab2e013aa4b8,accepted_at,2016-06-25 00:50:18,2016-06-25 00:50:18,2016,6,25,00:50:18,0,50,18,7
194072,fffe21d101e8c85fbf94b05bdb24c951,accepted_at,2016-06-09 08:24:59,2016-06-09 08:24:59,2016,6,9,08:24:59,8,24,59,17
194073,fffe87c305afa41349e56f63731e04ea,accepted_at,2016-05-04 22:02:34,2016-05-04 22:02:34,2016,5,4,22:02:34,22,2,34,10
194074,fffe942c46a5b2039fa01ba4c3d390e8,accepted_at,2016-05-17 19:56:13,2016-05-17 19:56:13,2016,5,17,19:56:13,19,56,13,4
194075,fffebb46effb90ce758fdff68b569355,accepted_at,2016-06-16 09:57:12,2016-06-16 09:57:12,2016,6,16,09:57:12,9,57,12,5
194076,ffff9c38173ddfa17bdd115c463e329f,accepted_at,2016-06-03 18:34:07,2016-06-03 18:34:07,2016,6,3,18:34:07,18,34,7,7
194077,ffff9e431f7fade54b2550ac19ab6e64,accepted_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10,0
194078,ffffa07f48f2f885f714765d794ad596,accepted_at,2016-04-19 01:09:12,2016-04-19 01:09:12,2016,4,19,01:09:12,1,8,72,15
194079,ffffccd77f47a3de26dfed9a851464b4,accepted_at,2016-05-18 08:44:21,2016-05-18 08:44:21,2016,5,18,08:44:21,8,44,21,8

THis is going to be the code where the average time that the driver drives is recorded, in relation to how important it is to have the drivers there based on the wait time that customers must wait.

In [70]:
my_wait_nums = list(table_arrived_at["wait_num"])

In [24]:
for i in range(len(my_wait_nums)):
    my_wait_nums[i] = abs(my_wait_nums[i])

In [78]:
table_arrived_at["ride_id"][44962]

'3b84986166ec87819f31edd49beb50b5'

In [27]:
table_arrived_at["actual_waittime"] = my_wait_nums

In [83]:
np.min(my_wait_nums)

0

In [ ]:
# table_arrived_at["wait time"] = table_arrived_at.groupby(["ride_id"]).agg({"wait time": np.diff()})
# table_arrived_at

both_tables = both_tables.groupby(['ride_id'])['wait_num'].sum()

both_tables = pd.DataFrame(both_tables)

In [ ]:
both_tables.sort_values("wait_num", ascending=True)

In [223]:
retention.to_csv('retention.csv')

In [215]:

ride_timestamps_df.loc[ride_timestamps_df['ride_id'] == "fff849783a408c12ea4b540fabdb9ab2"]

,ride_id,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds,wait_num
970270,fff849783a408c12ea4b540fabdb9ab2,requested_at,2016-05-29 12:13:44,2016-05-29 12:13:44,2016,5,29,12:13:44,12,13,44,0
970271,fff849783a408c12ea4b540fabdb9ab2,accepted_at,2016-05-29 12:14:21,2016-05-29 12:14:21,2016,5,29,12:14:21,12,14,21,0
970272,fff849783a408c12ea4b540fabdb9ab2,arrived_at,2016-05-29 12:22:44,2016-05-29 12:22:44,2016,5,29,12:22:44,12,22,44,0
970273,fff849783a408c12ea4b540fabdb9ab2,picked_up_at,2016-05-29 12:22:47,2016-05-29 12:22:47,2016,5,29,12:22:47,12,22,47,0
970274,fff849783a408c12ea4b540fabdb9ab2,dropped_off_at,2016-05-29 12:36:54,2016-05-29 12:36:54,2016,5,29,12:36:54,12,36,54,0

In [36]:
both_tables

,ride_id,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds,wait_num
0,00003037a262d9ee40e61b5c0718f7f0,arrived_at,2016-06-13 09:44:31,2016-06-13 09:44:31,2016,6,13,09:44:31,9,44,31,65
1,00005eae40882760d675da5effb89ae3,arrived_at,2016-05-14 05:26:17,2016-05-14 05:26:17,2016,5,14,05:26:17,5,26,17,63
2,000061d42cf29f73b591041d9a1b2973,arrived_at,2016-05-16 15:47:29,2016-05-16 15:47:29,2016,5,16,15:47:29,15,47,29,64
3,00006efeb0d5e3ccad7d921ddeee9900,arrived_at,2016-05-11 19:35:11,2016-05-11 19:35:11,2016,5,11,19:35:11,19,35,11,66
4,0000d9b24d8ccdd991b76258e616fa01,arrived_at,2016-04-26 18:16:52,2016-04-26 18:16:52,2016,4,26,18:16:52,18,16,52,65
5,00012759befd5d34a0609800f6a1ee59,arrived_at,2016-05-31 15:46:22,2016-05-31 15:46:22,2016,5,31,15:46:22,15,46,22,62
6,0001480a2c27492b1f8cb5fbc38ca667,arrived_at,2016-06-05 02:08:35,2016-06-05 02:08:35,2016,6,5,02:08:35,2,8,35,10
7,0002033cf1878734f3ffec9ad9748b3e,arrived_at,2016-05-28 21:05:27,2016-05-28 21:05:27,2016,5,28,21:05:27,21,5,27,62
8,0002090d41c4050b1683e3c4f69ed1c4,arrived_at,2016-06-23 16:19:46,2016-06-23 16:19:46,2016,6,23,16:19:46,16,19,46,67
9,00024c06e3554012303d4caa449222f3,arrived_at,2016-06-19 02:02:41,2016-06-19 02:02:41,2016,6,19,02:02:41,2,2,41,-53
10,000290b418595bfe228d2bf4d4e331df,arrived_at,2016-04-30 23:34:04,2016-04-30 23:34:04,2016,4,30,23:34:04,23,34,4,64
11,0002928349cb115e78e5a9e172f987f3,arrived_at,2016-06-10 03:58:05,2016-06-10 03:58:05,2016,6,10,03:58:05,3,58,5,80
12,00029ca867a194935a134297165152fc,arrived_at,2016-06-13 08:31:39,2016-06-13 08:31:39,2016,6,13,08:31:39,8,31,39,66
13,0002c4eccf2dac74132506de8087261e,arrived_at,2016-06-21 20:44:09,2016-06-21 20:44:09,2016,6,21,20:44:09,20,44,9,64
14,0002c71a866c07b68b5ff8cdfd003ea0,arrived_at,2016-05-30 19:55:40,2016-05-30 19:55:40,2016,5,30,19:55:40,19,55,40,68
15,000399d2e73490f5ac5e65eae391f6f8,arrived_at,2016-06-25 19:57:11,2016-06-25 19:57:11,2016,6,25,19:57:11,19,57,11,62
16,0003bd8128cced32fcb88aa3805b0a72,arrived_at,2016-04-26 21:23:40,2016-04-26 21:23:40,2016,4,26,21:23:40,21,23,40,62
17,000422a0d02abcf059a579d1cd60bdc9,arrived_at,2016-06-14 22:49:22,2016-06-14 22:49:22,2016,6,14,22:49:22,22,49,22,65
18,00046fb60349e54c9845d667d7c897fd,arrived_at,2016-05-08 02:00:55,2016-05-08 02:00:55,2016,5,8,02:00:55,2,0,55,-59
19,0004a3db0fb83d99007c394173660ac3,arrived_at,2016-05-27 01:19:32,2016-05-27 01:19:32,2016,5,27,01:19:32,1,19,32,61
20,0004b5e8b5df564779e20ce317f68c48,arrived_at,2016-05-07 22:45:20,2016-05-07 22:45:20,2016,5,7,22:45:20,22,45,20,63
21,0004d0b38d8b264cab0f03e34c2f52d3,arrived_at,2016-05-27 23:19:18,2016-05-27 23:19:18,2016,5,27,23:19:18,23,19,18,70
22,000527ec3aa73cc922d8a4858edf9c06,arrived_at,2016-04-13 22:58:00,2016-04-13 22:58:00,2016,4,13,22:58:00,22,58,0,63
23,00053e4ae1b3bfe921b3b499e4dc9ab3,arrived_at,2016-06-14 22:30:01,2016-06-14 22:30:01,2016,6,14,22:30:01,22,30,1,66
24,00058997f105bbd89b57fe0df10095c1,arrived_at,2016-05-25 23:25:59,2016-05-25 23:25:59,2016,5,25,23:25:59,23,25,59,60
25,00062b47908be1bf23ce194c0feca420,arrived_at,2016-06-14 16:03:43,2016-06-14 16:03:43,2016,6,14,16:03:43,16,3,43,-56
26,00070d6d3eb01e6444b7da3a68846507,arrived_at,2016-06-14 07:37:35,2016-06-14 07:37:35,2016,6,14,07:37:35,7,37,35,64
27,0007f92b090f91c4041c94bc2d6786e2,arrived_at,2016-06-12 19:57:14,2016-06-12 19:57:14,2016,6,12,19:57:14,19,57,14,66
28,0008072782166aada78a9da47b0e01fd,arrived_at,2016-04-26 13:02:31,2016-04-26 13:02:31,2016,4,26,13:02:31,13,2,31,-54
29,00088cf50ace520d5787c3a532f17e84,arrived_at,2016-05-23 12:42:57,2016-05-23 12:42:57,2016,5,23,12:42:57,12,42,57,64
...,...,...,...,...,...,...,...,...,...,...,...,...
388131,fff70949bfcaee69fb8f1558a0282dea,arrived_at,2016-04-29 16:43:55,2016-04-29 16:43:55,2016,4,29,16:43:55,16,43,55,0
388132,fff72f782408c2c894174b7a1e8cfc6e,arrived_at,2016-05-13 11:01:58,2016-05-13 11:01:58,2016,5,13,11:01:58,11,1,58,0
388133,fff78c33c0fd9d4b8d1cc8e59bee4961,arrived_at,2016-05-05 19:22:54,2016-05-05 19:22:54,2016,5,5,19:22:54,19,22,54,0
388134,fff849783a408c12ea4b540fabdb9ab2,arrived_at,2016-05-29 12:13:44,2016-05-29 12:13:44,2016,5,29,12:13:44,12,13,44,0
388135,fff870d2fd515aeaf6f9d2f5c224e613,arrived_at,2016-04-16 21:17:10,2016-04-16 21:17:10,2016,4,16,21:17:10,21,17,10,0
388136,fff876f91b10374effc1c7364d7962bf,arrived_at,2016-05-26 08:55:26,2016-05-26 08:55:26,2016,5,26,08:55:26,8,55,26,0
388137,fff8810affac74edfcdd09499ab4a848,arrived_at,2016-05-18 13:20:12,2016-05-18 13:20:12,2016,5,18,13:20:12,13,20,12,0
388138,fff8c7cca2a343ed675ddd39b742ec38,arrived_at,2016-06-24 20:07:00,2016-06-24 20:07:00,2016,6,24,20:07:00,20,7,0,0
388139,fff90d32189a6b8c37a6e0fb94a10327,arrived_at,2016-06-18 01:09:55,2016-06-18 01:09:55,2016,6,18,01:09:55,1,9,55,0
388140,fff9421eb58b06c24e07cc28bcb5a4ee,arrived_at,2016-05-06 08:30:04,2016-05-06 08:30:04,2016,5,6,08:30:04,8,30,4,0
388141,fff9820c5ed321c9b6cd3f027b37d318,arrived_at,2016-05-24 20:30:57,2016-05-24 20:30:57,2016,5,24,20:30:57,20,30,57,0
388142,fff9866958f16d0d76211b330ef5d772,arrived_at,2016-06-13 09:53:17,2016-06-13 09:53:17,2016,6,13,09:53:17,9,53,17,0
388143,fff9f2a133a87087a48c76eaf21d76fc,arrived_at,2016-05-03 09:19:31,2016-05-03 09:19:31,2016,5,3,09:19:31,9,19,31,0
388144,fffa06c45bc021b13cb6bc3c2679e8e0,arrived_at,2016-06-09 18:44:54,2016-06-09 18:44:54,2016,6,9,18:44:54,18,44,54,0
388145,fffa5815788aa758c8aa3f839860f57e,arrived_at,2016-06-10 21:55:00,2016-06-10 21:55:00,2016,6,10,21:55:00,21,55,0,0
388146,fffa6e36c119735b739307ec15b52a04,arrived_at,2016-05-05 21:30:58,2016-05-05 21:30:58,2016,5,5,21:30:58,21,30,58,0
388147,fffab94b777130200293f7233faa80f7,arrived_at,2016-04-29 09:55:03,2016-04-29 09:55:03,2016,4,29,09:55:03,9,55,3,0
388148,fffad62798420b83b5f179edc4260dd2,arrived_at,2016-06-23 14:40:34,2016-06-23 14:40:34,2016,6,23,14:40:34,14,40,34,0
388149,fffbdc0bbb975217401bdd24d66a3ac9,arrived_at,2016-05-29 21:54:13,2016-05-29 21:54:13,2016,5,29,21:54:13,21,54,13,0
388150,fffcf368d05983e45d910d714ac80819,arrived_at,2016-06-23 08:14:20,2016-06-23 08:14:20,2016,6,23,08:14:20,8,14,20,0
388151,fffd6c6bdfb2ecafe031797a5afba4a0,arrived_at,2016-06-24 09:00:21,2016-06-24 09:00:21,2016,6,24,09:00:21,9,0,21,0
388152,fffd9426f1c055691ae1ab2e013aa4b8,arrived_at,2016-06-25 00:50:11,2016-06-25 00:50:11,2016,6,25,00:50:11,0,50,11,0
388153,fffe21d101e8c85fbf94b05bdb24c951,arrived_at,2016-06-09 08:24:42,2016-06-09 08:24:42,2016,6,9,08:24:42,8,24,42,0
388154,fffe87c305afa41349e56f63731e04ea,arrived_at,2016-05-04 22:02:24,2016-05-04 22:02:24,2016,5,4,22:02:24,22,2,24,0
388155,fffe942c46a5b2039fa01ba4c3d390e8,arrived_at,2016-05-17 19:56:09,2016-05-17 19:56:09,2016,5,17,19:56:09,19,56,9,0
388156,fffebb46effb90ce758fdff68b569355,arrived_at,2016-06-16 09:57:07,2016-06-16 09:57:07,2016,6,16,09:57:07,9,57,7,0
388157,ffff9c38173ddfa17bdd115c463e329f,arrived_at,2016-06-03 18:34:00,2016-06-03 18:34:00,2016,6,3,18:34:00,18,34,0,0
388158,ffff9e431f7fade54b2550ac19ab6e64,arrived_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10,0
388159,ffffa07f48f2f885f714765d794ad596,arrived_at,2016-04-19 01:08:57,2016-04-19 01:08:57,2016,4,19,01:08:57,1,8,57,0
388160,ffffccd77f47a3de26dfed9a851464b4,arrived_at,2016-05-18 08:44:13,2016-05-18 08:44:13,2016,5,18,08:44:13,8,44,13,0

NameError: name 'both_tables' is not defined

In [5]:
np.min(wait_nums["wait_num"])

1

In [86]:
len(ride_timestamps_df)
# group by drivers id
# to see number of rides per driver
grouped = ride_ids_df.groupby('driver_id')
grouped.first()

,ride_id,ride_distance,ride_duration,ride_prime_time
driver_id,,,,
002be0ffdc997bd5c50703158b7c2491,006d61cf7446e682f7bc50b0f8a5bea5,1811,327,50
007f0389f9c7b03ef97098422f902e62,01f133164433ea7682545a41643e6949,4711,856,25
011e5c5dfc5c2c92501b8b24d47509bc,0912947c9f3ff530407cd150a4cea97c,1148,223,0
0152a2f305e71d26cc964f8d4411add9,014aa63435baaed30b21e12ae30f3797,2931,599,0
01674381af7edd264113d4e6ed55ecda,010c383f0ad4203666b749a2e9f25069,972,282,0
0213f8b59219e32142711992ca4ec01f,0177d0cf5a6638fa17275f3a3abf016a,6974,787,0
021e5cd15ef0bb3ec20a12af99e142b3,06122e557cee834bb73ace6e113a1ddc,10761,1262,25
0258e250ca195cc6258cbdc75aecd853,001c265aa128691fe7905e71826849d9,3429,623,0
028b5a4dcd7f4924ebfabcf2e814c014,002413f7dc2c315fc2e89c1cfc2bb2ae,4017,798,0
02d6a6b8a6da15fc219a9570f7ebbe78,02c7ebb52d08f937f30cc218bbaea984,35655,2866,0
02e440f6c209206375833cef02e0cbae,080cf659a52577e91ca2b2ff06907bbe,2535,563,0
036f3d94e7c65e4e3574822d31c72656,02726ef22e10d3c4542153b56445c97d,3916,728,25
039c5afbca8e03e4c18d9c8ea94140ac,054c0f9258daf07ca16e88d9b7a688e6,1357,448,0
039da9c077e17af98ca8530e4d7975f1,006098449a0e04dac06a391e33e82349,7708,1159,50
03f2b5c74cb89f39e58711699e76bf39,017af2bf5c8f530f50ac4a9aabf3cad8,1211,223,0
03f5278eb43475aa6790f5be32463755,000e214f8f52e5853add607878553fb1,1898,285,0
0430df9a3eb327122c57ee3a64765000,013e4abc76ee3a48e384ab30af02d73e,887,244,0
04c4ffa5a385eab86fa7e422263d2999,06bd53ceeeb8764765d7e8b4fb24fd2e,26237,2745,0
04d686ef2fba281e395992a28f14fdd3,024a4423f5563cfd46401c0386412964,22666,1285,0
052bba06c5fc0bdea4bc2f9cb92b37c7,0794cee7f8d8fc67829e870d4beb255a,2194,377,0
056175954c78be4c4de7e80167b7e1f9,0488679087be6f76612dfc9ecba227e5,2069,407,0
059ed570673c2d15ca11dd6b3a25513b,069aa6ffdfcc320b6aba64a84c3661b3,20648,1976,0
05addf442c147875efa5cf53453ad47b,005ef23a76471b7ae664bb4e9f97e2da,3833,1289,75
05bad02e08c7f849e91dc1259da8b4ec,04d79e078d803aa2fa2b9ffb2c389ffc,3620,557,0
0656192a402808805282e60761bda088,00005eae40882760d675da5effb89ae3,3016,479,25
06b1ba06e5505f8218ec8686498f990a,03e2b8fa61b2a2e76d1fa3294ced710f,11138,1435,0
06c848ab3a7fc5421e82e98850a81710,00d6059fd7f2ac68f9fa5f3ab05e08b0,10454,891,0
07dd442e3e0b9f0f9b0d69c7b47cbb06,002c45d2f9029b99a8955c1766d0b8fc,1774,451,0
07e6a2fdaadc640cca9a7bec41351065,03fb04fd829c54c92cb692e5744e79ac,1598,207,0
081d8ba3bc9a00a481df02bd9d0a4c53,004d1da707b1b95f27e4966368ddfcea,23004,1401,0
...,...,...,...,...
f7858e1e354a9fa26b3055bc12a4ee5b,0058d1362716cae2c038ee27079b3971,1659,402,0
f86eb77e1cefe28e9f0e9d3775fae261,0109ae8aa17377fc8b862516b0b635b2,1543,336,0
f91254f1c1b3112ef3464e477d23c9e8,00c39402532200b7357970a0056641c1,1105,250,0
f98673773627b4b8d152e2b168b85bb2,0753dd5eb009ffa37198f9433ec8b2e5,12930,1097,0
f9aa6d69d74e786544027a1ab3049f44,01320aadb595769ddb59a38a3e79f5ec,2901,559,0
fac81ea6cbd540c89c7eee17e851a233,001ade7b0726b9cdf85fc503e398671a,4443,713,0
faebff3d5429ff2036c125a91df765c8,015e54bf50b8e7be587715658181642e,6937,1211,0
fb83fc6555a4f700fd92630d9fcb9cea,00e493a3d7b73586912ed4c5c32d0127,7703,1601,50
fb903879c556260ae2604ae0c45cb92a,00841f657231470a1b9e7b37ecd071b4,21985,1367,0
fba8372d56b91b1bff7b71d970b5af58,01ee3bbfc47ed78f4ee2d6537769602f,32329,1674,50
fbe0433e5b1a3db9dc9d6ed21efc6148,061c52513541f477e0142e93e4551f3f,5111,823,25
fc3504d2efaaaa976a33b3c856927155,007489cd80a1f9fe28b885b0585e0172,5357,686,0
fc83b793850ea70d9e898afd0b3ef592,00f6114fcecf8936c7b706f0837eb32c,2632,514,0
fd2130d0d215069168dc2f79c1f5ae44,00299e4845427b9022b66f2f5529dfd0,6978,933,75
fd39748ba122e84e9ac492e6fb7c7a05,009c092466c365b59b9344ee731de35c,2213,550,0
fd831ca1d79ae5c6fc3a679a22e5b8cf,0a7ed4ae3a3433ee8959fef5644f0471,6349,1079,0
fda96e6cd3395dfae3e59cd4ac95f7d7,011e040693b06909aba3a797b1cc7f98,2126,583,100
fdbee494c73577d5b1266d1fec5c6c9a,007ab2b768c507d925962460f053129a,4986,457,0
fde60697758e68d617f471e49f65db75,00fadc267e60b5404cc0cba3c4749357,24556,1927,25
fdff1a7205bc3b9ab1dc5dc223782fc5,0015805e425aeceb26395b08b592184c,26833,1565,50
fe35f74209d1056dd315ddb17681203d,0052ebc3cc62d38886d95024cb2a6467,2135,443,0
fe469488a23d4bdda47b83a659dcc103,0021d91a9dff2a5171f7927e84937801,2408,454,0
fed19d671569afe8a2f9fa0953dd25ca,07fbc77afc263b5892d427c662e7d7cb,3630,731,50
ff1bb46e6b61766f4c7b9abd0a4ef9ac,00ed9f7dc5810fc14dd14d7459cf2efa,11410,1061,50
ff419a3476e21e269e340b5f1f05414e,004cfe236df5ba2bb44405c14ac4d714,1643,493,0
ff45a18cae7bed6538847cb36e2a3975,00ece2c9214008915c5217b4ad53eb7b,32707,1651,0
ff714a67ba8c6a108261cd81e3b77f3a,0016e5d573f909c6ec203b57eb7f9a7b,1900,440,0
fff482c704d36a1afe8b8978d5486283,05639c0819d061fd0c8ed34a098dfb45,7165,761,0
fffecccc49436c5389075b13209f0dfa,001d27dd0b5c59cc8e406e334d93dee8,6704,1012,0
ffff51a71f2f185ec5e97d59dbcd7a78,0108e190c7850ecd522efa2c3204dbf8,4628,722,0




Need to find the latest date that the driver has driven


This is the work that i did in order to find the last time that a driver has driven!!! some of the drivers did not drive???

,ride_id,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds,wait_num
0,00003037a262d9ee40e61b5c0718f7f0,requested_at,2016-06-13 09:39:19,2016-06-13 09:39:19,2016,6,13,09:39:19,9,39,19,0
1,00003037a262d9ee40e61b5c0718f7f0,accepted_at,2016-06-13 09:39:51,2016-06-13 09:39:51,2016,6,13,09:39:51,9,39,51,0
2,00003037a262d9ee40e61b5c0718f7f0,arrived_at,2016-06-13 09:44:31,2016-06-13 09:44:31,2016,6,13,09:44:31,9,44,31,0
3,00003037a262d9ee40e61b5c0718f7f0,picked_up_at,2016-06-13 09:44:33,2016-06-13 09:44:33,2016,6,13,09:44:33,9,44,33,0
4,00003037a262d9ee40e61b5c0718f7f0,dropped_off_at,2016-06-13 10:03:05,2016-06-13 10:03:05,2016,6,13,10:03:05,10,3,5,0
5,00005eae40882760d675da5effb89ae3,requested_at,2016-05-14 05:23:21,2016-05-14 05:23:21,2016,5,14,05:23:21,5,23,21,0
6,00005eae40882760d675da5effb89ae3,accepted_at,2016-05-14 05:23:25,2016-05-14 05:23:25,2016,5,14,05:23:25,5,23,25,0
7,00005eae40882760d675da5effb89ae3,arrived_at,2016-05-14 05:26:17,2016-05-14 05:26:17,2016,5,14,05:26:17,5,26,17,0
8,00005eae40882760d675da5effb89ae3,picked_up_at,2016-05-14 05:26:18,2016-05-14 05:26:18,2016,5,14,05:26:18,5,26,18,0
9,00005eae40882760d675da5effb89ae3,dropped_off_at,2016-05-14 05:34:17,2016-05-14 05:34:17,2016,5,14,05:34:17,5,34,17,0
10,000061d42cf29f73b591041d9a1b2973,requested_at,2016-05-16 15:43:09,2016-05-16 15:43:09,2016,5,16,15:43:09,15,43,9,0
11,000061d42cf29f73b591041d9a1b2973,accepted_at,2016-05-16 15:43:14,2016-05-16 15:43:14,2016,5,16,15:43:14,15,43,14,0
12,000061d42cf29f73b591041d9a1b2973,arrived_at,2016-05-16 15:47:29,2016-05-16 15:47:29,2016,5,16,15:47:29,15,47,29,0
13,000061d42cf29f73b591041d9a1b2973,picked_up_at,2016-05-16 15:47:32,2016-05-16 15:47:32,2016,5,16,15:47:32,15,47,32,0
14,000061d42cf29f73b591041d9a1b2973,dropped_off_at,2016-05-16 15:54:18,2016-05-16 15:54:18,2016,5,16,15:54:18,15,54,18,0
15,00006efeb0d5e3ccad7d921ddeee9900,requested_at,2016-05-11 19:29:36,2016-05-11 19:29:36,2016,5,11,19:29:36,19,29,36,0
16,00006efeb0d5e3ccad7d921ddeee9900,accepted_at,2016-05-11 19:29:43,2016-05-11 19:29:43,2016,5,11,19:29:43,19,29,43,0
17,00006efeb0d5e3ccad7d921ddeee9900,arrived_at,2016-05-11 19:35:11,2016-05-11 19:35:11,2016,5,11,19:35:11,19,35,11,0
18,00006efeb0d5e3ccad7d921ddeee9900,picked_up_at,2016-05-11 19:35:15,2016-05-11 19:35:15,2016,5,11,19:35:15,19,35,15,0
19,00006efeb0d5e3ccad7d921ddeee9900,dropped_off_at,2016-05-11 19:40:47,2016-05-11 19:40:47,2016,5,11,19:40:47,19,40,47,0
20,0000d9b24d8ccdd991b76258e616fa01,requested_at,2016-04-26 18:11:38,2016-04-26 18:11:38,2016,4,26,18:11:38,18,11,38,0
21,0000d9b24d8ccdd991b76258e616fa01,accepted_at,2016-04-26 18:12:15,2016-04-26 18:12:15,2016,4,26,18:12:15,18,12,15,0
22,0000d9b24d8ccdd991b76258e616fa01,arrived_at,2016-04-26 18:16:52,2016-04-26 18:16:52,2016,4,26,18:16:52,18,16,52,0
23,0000d9b24d8ccdd991b76258e616fa01,picked_up_at,2016-04-26 18:16:55,2016-04-26 18:16:55,2016,4,26,18:16:55,18,16,55,0
24,0000d9b24d8ccdd991b76258e616fa01,dropped_off_at,2016-04-26 18:24:14,2016-04-26 18:24:14,2016,4,26,18:24:14,18,24,14,0
25,00012759befd5d34a0609800f6a1ee59,requested_at,2016-05-31 15:44:56,2016-05-31 15:44:56,2016,5,31,15:44:56,15,44,56,0
26,00012759befd5d34a0609800f6a1ee59,accepted_at,2016-05-31 15:45:05,2016-05-31 15:45:05,2016,5,31,15:45:05,15,45,5,0
27,00012759befd5d34a0609800f6a1ee59,arrived_at,2016-05-31 15:46:22,2016-05-31 15:46:22,2016,5,31,15:46:22,15,46,22,0
28,00012759befd5d34a0609800f6a1ee59,picked_up_at,2016-05-31 15:46:23,2016-05-31 15:46:23,2016,5,31,15:46:23,15,46,23,0
29,00012759befd5d34a0609800f6a1ee59,dropped_off_at,2016-05-31 15:59:26,2016-05-31 15:59:26,2016,5,31,15:59:26,15,59,26,0
...,...,...,...,...,...,...,...,...,...,...,...,...
970375,fffe942c46a5b2039fa01ba4c3d390e8,requested_at,2016-05-17 19:56:09,2016-05-17 19:56:09,2016,5,17,19:56:09,19,56,9,0
970376,fffe942c46a5b2039fa01ba4c3d390e8,accepted_at,2016-05-17 19:56:13,2016-05-17 19:56:13,2016,5,17,19:56:13,19,56,13,0
970377,fffe942c46a5b2039fa01ba4c3d390e8,arrived_at,2016-05-17 19:58:50,2016-05-17 19:58:50,2016,5,17,19:58:50,19,58,50,0
970378,fffe942c46a5b2039fa01ba4c3d390e8,picked_up_at,2016-05-17 19:58:52,2016-05-17 19:58:52,2016,5,17,19:58:52,19,58,52,0
970379,fffe942c46a5b2039fa01ba4c3d390e8,dropped_off_at,2016-05-17 20:11:11,2016-05-17 20:11:11,2016,5,17,20:11:11,20,11,11,0
970380,fffebb46effb90ce758fdff68b569355,requested_at,2016-06-16 09:57:07,2016-06-16 09:57:07,2016,6,16,09:57:07,9,57,7,0
970381,fffebb46effb90ce758fdff68b569355,accepted_at,2016-06-16 09:57:12,2016-06-16 09:57:12,2016,6,16,09:57:12,9,57,12,0
970382,fffebb46effb90ce758fdff68b569355,arrived_at,2016-06-16 09:58:54,2016-06-16 09:58:54,2016,6,16,09:58:54,9,58,54,0
970383,fffebb46effb90ce758fdff68b569355,picked_up_at,2016-06-16 09:58:57,2016-06-16 09:58:57,2016,6,16,09:58:57,9,58,57,0
970384,fffebb46effb90ce758fdff68b569355,dropped_off_at,2016-06-16 10:15:08,2016-06-16 10:15:08,2016,6,16,10:15:08,10,15,8,0
970385,ffff9c38173ddfa17bdd115c463e329f,requested_at,2016-06-03 18:34:00,2016-06-03 18:34:00,2016,6,3,18:34:00,18,34,0,0
970386,ffff9c38173ddfa17bdd115c463e329f,accepted_at,2016-06-03 18:34:07,2016-06-03 18:34:07,2016,6,3,18:34:07,18,34,7,0
970387,ffff9c38173ddfa17bdd115c463e329f,arrived_at,2016-06-03 18:35:20,2016-06-03 18:35:20,2016,6,3,18:35:20,18,35,20,0
970388,ffff9c38173ddfa17bdd115c463e329f,picked_up_at,2016-06-03 18:35:22,2016-06-03 18:35:22,2016,6,3,18:35:22,18,35,22,0
970389,ffff9c38173ddfa17bdd115c463e329f,dropped_off_at,2016-06-03 18:50:08,2016-06-03 18:50:08,2016,6,3,18:50:08,18,50,8,0
970390,ffff9e431f7fade54b2550ac19ab6e64,requested_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10,0
970391,ffff9e431f7fade54b2550ac19ab6e64,accepted_at,2016-06-12 04:00:10,2016-06-12 04:00:10,2016,6,12,04:00:10,4,0,10,0
970392,ffff9e431f7fade54b2550ac19ab6e64,arrived_at,2016-06-12 04:04:35,2016-06-12 04:04:35,2016,6,12,04:04:35,4,4,35,0
970393,ffff9e431f7fade54b2550ac19ab6e64,picked_up_at,2016-06-12 04:04:37,2016-06-12 04:04:37,2016,6,12,04:04:37,4,4,37,0
970394,ffff9e431f7fade54b2550ac19ab6e64,dropped_off_at,2016-06-12 04:15:42,2016-06-12 04:15:42,2016,6,12,04:15:42,4,15,42,0
970395,ffffa07f48f2f885f714765d794ad596,requested_at,2016-04-19 01:08:57,2016-04-19 01:08:57,2016,4,19,01:08:57,1,8,57,0
970396,ffffa07f48f2f885f714765d794ad596,accepted_at,2016-04-19 01:09:12,2016-04-19 01:09:12,2016,4,19,01:09:12,1,9,12,0
970397,ffffa07f48f2f885f714765d794ad596,arrived_at,2016-04-19 01:10:49,2016-04-19 01:10:49,2016,4,19,01:10:49,1,10,49,0
970398,ffffa07f48f2f885f714765d794ad596,picked_up_at,2016-04-19 01:10:50,2016-04-19 01:10:50,2016,4,19,01:10:50,1,10,50,0
970399,ffffa07f48f2f885f714765d794ad596,dropped_off_at,2016-04-19 01:30:48,2016-04-19 01:30:48,2016,4,19,01:30:48,1,30,48,0
970400,ffffccd77f47a3de26dfed9a851464b4,requested_at,2016-05-18 08:44:13,2016-05-18 08:44:13,2016,5,18,08:44:13,8,44,13,0
970401,ffffccd77f47a3de26dfed9a851464b4,accepted_at,2016-05-18 08:44:21,2016-05-18 08:44:21,2016,5,18,08:44:21,8,44,21,0
970402,ffffccd77f47a3de26dfed9a851464b4,arrived_at,2016-05-18 08:44:36,2016-05-18 08:44:36,2016,5,18,08:44:36,8,44,36,0
970403,ffffccd77f47a3de26dfed9a851464b4,picked_up_at,2016-05-18 08:44:42,2016-05-18 08:44:42,2016,5,18,08:44:42,8,44,42,0
970404,ffffccd77f47a3de26dfed9a851464b4,dropped_off_at,2016-05-18 09:11:37,2016-05-18 09:11:37,2016,5,18,09:11:37,9,11,37,0

In [100]:
result = pd.merge(ride_ids_df, ride_timestamps_df, on='ride_id')
result = result.sort_values("timestamp")

In [101]:
result

,driver_id,ride_id,ride_distance,ride_duration,ride_prime_time,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds,wait_num
882200,f0df79d10df44f18742682108b17f60a,655ccbeb2a62880159e20e986c1cdaeb,40812,2112,25,requested_at,2016-03-28 05:48:18,2016-03-28 05:48:18,2016,3,28,05:48:18,5,48,18,0
882201,f0df79d10df44f18742682108b17f60a,655ccbeb2a62880159e20e986c1cdaeb,40812,2112,25,accepted_at,2016-03-28 05:48:23,2016-03-28 05:48:23,2016,3,28,05:48:23,5,48,23,0
882202,f0df79d10df44f18742682108b17f60a,655ccbeb2a62880159e20e986c1cdaeb,40812,2112,25,arrived_at,2016-03-28 06:02:36,2016-03-28 06:02:36,2016,3,28,06:02:36,6,2,36,0
882203,f0df79d10df44f18742682108b17f60a,655ccbeb2a62880159e20e986c1cdaeb,40812,2112,25,picked_up_at,2016-03-28 06:02:39,2016-03-28 06:02:39,2016,3,28,06:02:39,6,2,39,0
882204,f0df79d10df44f18742682108b17f60a,655ccbeb2a62880159e20e986c1cdaeb,40812,2112,25,dropped_off_at,2016-03-28 06:37:51,2016-03-28 06:37:51,2016,3,28,06:37:51,6,37,51,0
919990,ff714a67ba8c6a108261cd81e3b77f3a,e81c8bdc2a6a9056ba49bf67bf97c311,9384,1653,0,requested_at,2016-03-28 08:11:39,2016-03-28 08:11:39,2016,3,28,08:11:39,8,11,39,0
919991,ff714a67ba8c6a108261cd81e3b77f3a,e81c8bdc2a6a9056ba49bf67bf97c311,9384,1653,0,accepted_at,2016-03-28 08:11:44,2016-03-28 08:11:44,2016,3,28,08:11:44,8,11,44,0
919992,ff714a67ba8c6a108261cd81e3b77f3a,e81c8bdc2a6a9056ba49bf67bf97c311,9384,1653,0,arrived_at,2016-03-28 08:14:12,2016-03-28 08:14:12,2016,3,28,08:14:12,8,14,12,0
919993,ff714a67ba8c6a108261cd81e3b77f3a,e81c8bdc2a6a9056ba49bf67bf97c311,9384,1653,0,picked_up_at,2016-03-28 08:14:13,2016-03-28 08:14:13,2016,3,28,08:14:13,8,14,13,0
919994,ff714a67ba8c6a108261cd81e3b77f3a,e81c8bdc2a6a9056ba49bf67bf97c311,9384,1653,0,dropped_off_at,2016-03-28 08:41:46,2016-03-28 08:41:46,2016,3,28,08:41:46,8,41,46,0
919775,ff714a67ba8c6a108261cd81e3b77f3a,d113a5d0e13f2ddd041806aa5b1d90c8,22779,1953,0,requested_at,2016-03-28 08:44:16,2016-03-28 08:44:16,2016,3,28,08:44:16,8,44,16,0
919776,ff714a67ba8c6a108261cd81e3b77f3a,d113a5d0e13f2ddd041806aa5b1d90c8,22779,1953,0,accepted_at,2016-03-28 08:44:21,2016-03-28 08:44:21,2016,3,28,08:44:21,8,44,21,0
919777,ff714a67ba8c6a108261cd81e3b77f3a,d113a5d0e13f2ddd041806aa5b1d90c8,22779,1953,0,arrived_at,2016-03-28 08:48:09,2016-03-28 08:48:09,2016,3,28,08:48:09,8,48,9,0
919778,ff714a67ba8c6a108261cd81e3b77f3a,d113a5d0e13f2ddd041806aa5b1d90c8,22779,1953,0,picked_up_at,2016-03-28 08:48:13,2016-03-28 08:48:13,2016,3,28,08:48:13,8,48,13,0
547680,8eb2f1fd0858319b86b9e44b64660eb6,e8564242d0aec402e965befa8529ed62,22748,2049,0,requested_at,2016-03-28 08:51:23,2016-03-28 08:51:23,2016,3,28,08:51:23,8,51,23,0
547681,8eb2f1fd0858319b86b9e44b64660eb6,e8564242d0aec402e965befa8529ed62,22748,2049,0,accepted_at,2016-03-28 08:51:52,2016-03-28 08:51:52,2016,3,28,08:51:52,8,51,52,0
547682,8eb2f1fd0858319b86b9e44b64660eb6,e8564242d0aec402e965befa8529ed62,22748,2049,0,arrived_at,2016-03-28 08:54:32,2016-03-28 08:54:32,2016,3,28,08:54:32,8,54,32,0
547683,8eb2f1fd0858319b86b9e44b64660eb6,e8564242d0aec402e965befa8529ed62,22748,2049,0,picked_up_at,2016-03-28 08:54:36,2016-03-28 08:54:36,2016,3,28,08:54:36,8,54,36,0
495760,7f4350f4a358ac264ccf3b10c4966afc,c5f5ce67e46d268585c5c0fa0cdee78d,3602,571,25,requested_at,2016-03-28 09:15:23,2016-03-28 09:15:23,2016,3,28,09:15:23,9,15,23,0
495761,7f4350f4a358ac264ccf3b10c4966afc,c5f5ce67e46d268585c5c0fa0cdee78d,3602,571,25,accepted_at,2016-03-28 09:15:28,2016-03-28 09:15:28,2016,3,28,09:15:28,9,15,28,0
919779,ff714a67ba8c6a108261cd81e3b77f3a,d113a5d0e13f2ddd041806aa5b1d90c8,22779,1953,0,dropped_off_at,2016-03-28 09:20:46,2016-03-28 09:20:46,2016,3,28,09:20:46,9,20,46,0
495762,7f4350f4a358ac264ccf3b10c4966afc,c5f5ce67e46d268585c5c0fa0cdee78d,3602,571,25,arrived_at,2016-03-28 09:24:46,2016-03-28 09:24:46,2016,3,28,09:24:46,9,24,46,0
495763,7f4350f4a358ac264ccf3b10c4966afc,c5f5ce67e46d268585c5c0fa0cdee78d,3602,571,25,picked_up_at,2016-03-28 09:24:50,2016-03-28 09:24:50,2016,3,28,09:24:50,9,24,50,0
275565,479c3dccc06056867dd10c7d9fa0f569,c7f00b36bf7c4c02fc6a63f1d3e77289,4114,943,25,requested_at,2016-03-28 09:27:25,2016-03-28 09:27:25,2016,3,28,09:27:25,9,27,25,0
275566,479c3dccc06056867dd10c7d9fa0f569,c7f00b36bf7c4c02fc6a63f1d3e77289,4114,943,25,accepted_at,2016-03-28 09:28:00,2016-03-28 09:28:00,2016,3,28,09:28:00,9,28,0,0
547684,8eb2f1fd0858319b86b9e44b64660eb6,e8564242d0aec402e965befa8529ed62,22748,2049,0,dropped_off_at,2016-03-28 09:28:45,2016-03-28 09:28:45,2016,3,28,09:28:45,9,28,45,0
919970,ff714a67ba8c6a108261cd81e3b77f3a,e523dbf8f966d9d34569d4853df3c9cc,24322,2887,50,requested_at,2016-03-28 09:30:59,2016-03-28 09:30:59,2016,3,28,09:30:59,9,30,59,0
919971,ff714a67ba8c6a108261cd81e3b77f3a,e523dbf8f966d9d34569d4853df3c9cc,24322,2887,50,accepted_at,2016-03-28 09:31:03,2016-03-28 09:31:03,2016,3,28,09:31:03,9,31,3,0
275567,479c3dccc06056867dd10c7d9fa0f569,c7f00b36bf7c4c02fc6a63f1d3e77289,4114,943,25,arrived_at,2016-03-28 09:32:05,2016-03-28 09:32:05,2016,3,28,09:32:05,9,32,5,0
275568,479c3dccc06056867dd10c7d9fa0f569,c7f00b36bf7c4c02fc6a63f1d3e77289,4114,943,25,picked_up_at,2016-03-28 09:32:06,2016-03-28 09:32:06,2016,3,28,09:32:06,9,32,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128554,2494554e7702a28816717bc0cbf7d57b,ac323f1e3df2e4739f871e762770aeb5,1922,427,0,dropped_off_at,2016-06-26 23:57:13,2016-06-26 23:57:13,2016,6,26,23:57:13,23,57,13,0
546514,8dbfef11a650dd9658ca0c6f70b84f88,f733b98ab31e7abc5e7a8bec5fad29a0,4731,997,25,dropped_off_at,2016-06-26 23:57:19,2016-06-26 23:57:19,2016,6,26,23:57:19,23,57,19,0
302949,50eadd94fd0152fd0638a915061c4c94,c91436292acc91ba5ad3acf8e8e81a50,4088,528,0,dropped_off_at,2016-06-26 23:57:30,2016-06-26 23:57:30,2016,6,26,23:57:30,23,57,30,0
21952,0656192a402808805282e60761bda088,e51093e307953ecf29061fb83aee3081,3214,419,0,arrived_at,2016-06-26 23:57:42,2016-06-26 23:57:42,2016,6,26,23:57:42,23,57,42,0
545575,8dbfef11a650dd9658ca0c6f70b84f88,311542541524c0d356fa8d7fc229baae,2546,388,25,requested_at,2016-06-26 23:57:45,2016-06-26 23:57:45,2016,6,26,23:57:45,23,57,45,0
545576,8dbfef11a650dd9658ca0c6f70b84f88,311542541524c0d356fa8d7fc229baae,2546,388,25,accepted_at,2016-06-26 23:57:49,2016-06-26 23:57:49,2016,6,26,23:57:49,23,57,49,0
227679,3caf85a7d6b8f5615fbc21e8310af584,c3d72d35b8213d432f107b2fbac849cd,1407,260,0,dropped_off_at,2016-06-26 23:58:20,2016-06-26 23:58:20,2016,6,26,23:58:20,23,58,20,0
21953,0656192a402808805282e60761bda088,e51093e307953ecf29061fb83aee3081,3214,419,0,picked_up_at,2016-06-26 23:58:28,2016-06-26 23:58:28,2016,6,26,23:58:28,23,58,28,0
545577,8dbfef11a650dd9658ca0c6f70b84f88,311542541524c0d356fa8d7fc229baae,2546,388,25,arrived_at,2016-06-26 23:59:01,2016-06-26 23:59:01,2016,6,26,23:59:01,23,59,1,0
545578,8dbfef11a650dd9658ca0c6f70b84f88,311542541524c0d356fa8d7fc229baae,2546,388,25,picked_up_at,2016-06-26 23:59:02,2016-06-26 23:59:02,2016,6,26,23:59:02,23,59,2,0
403122,689bdf87fb2de49f98bf4946cfaa5068,cd44d244f302709c84f21c56de437504,2947,453,0,arrived_at,2016-06-26 23:59:25,2016-06-26 23:59:25,2016,6,26,23:59:25,23,59,25,0
417599,6b65c06851e944351dd285a1eb729499,690fe116339622f72af07f2f269b8521,5271,420,0,dropped_off_at,2016-06-26 23:59:25,2016-06-26 23:59:25,2016,6,26,23:59:25,23,59,25,0
403123,689bdf87fb2de49f98bf4946cfaa5068,cd44d244f302709c84f21c56de437504,2947,453,0,picked_up_at,2016-06-27 00:00:21,2016-06-27 00:00:21,2016,6,27,00:00:21,0,0,21,0
331677,5943b68c2fa8bcfd0add30691fd9136b,bf49073d4b4369bb0e08a2d36e1cd097,23035,1163,0,arrived_at,2016-06-27 00:01:06,2016-06-27 00:01:06,2016,6,27,00:01:06,0,1,6,0
331678,5943b68c2fa8bcfd0add30691fd9136b,bf49073d4b4369bb0e08a2d36e1cd097,23035,1163,0,picked_up_at,2016-06-27 00:01:09,2016-06-27 00:01:09,2016,6,27,00:01:09,0,1,9,0
760374,cbba49117a03fd2f578022eab904dced,cb283287700d34c276682909c36aa99f,6319,568,25,dropped_off_at,2016-06-27 00:01:35,2016-06-27 00:01:35,2016,6,27,00:01:35,0,1,35,0
726459,c0640121b56458ccc0d2892067bc463b,e015a43686af84d5c1ae6f56dd1122aa,3984,890,0,dropped_off_at,2016-06-27 00:02:01,2016-06-27 00:02:01,2016,6,27,00:02:01,0,2,1,0
924052,ffff51a71f2f185ec5e97d59dbcd7a78,f90966687aebca6cc9efcd9e42897b75,20668,1469,0,arrived_at,2016-06-27 00:02:03,2016-06-27 00:02:03,2016,6,27,00:02:03,0,2,3,0
924053,ffff51a71f2f185ec5e97d59dbcd7a78,f90966687aebca6cc9efcd9e42897b75,20668,1469,0,picked_up_at,2016-06-27 00:02:06,2016-06-27 00:02:06,2016,6,27,00:02:06,0,2,6,0
847374,e76529a86a5efc221a88a6c91a75ea59,ba31b0623e6f7c35033c107553376a35,8065,764,0,dropped_off_at,2016-06-27 00:04:29,2016-06-27 00:04:29,2016,6,27,00:04:29,0,4,29,0
21954,0656192a402808805282e60761bda088,e51093e307953ecf29061fb83aee3081,3214,419,0,dropped_off_at,2016-06-27 00:05:27,2016-06-27 00:05:27,2016,6,27,00:05:27,0,5,27,0
545579,8dbfef11a650dd9658ca0c6f70b84f88,311542541524c0d356fa8d7fc229baae,2546,388,25,dropped_off_at,2016-06-27 00:05:30,2016-06-27 00:05:30,2016,6,27,00:05:30,0,5,30,0
859539,ec78920915122cbe500fcb475a8fb5d3,8a18c5c67f4a7bb8f1ee3f482eb61727,11262,713,0,dropped_off_at,2016-06-27 00:06:20,2016-06-27 00:06:20,2016,6,27,00:06:20,0,6,20,0
403124,689bdf87fb2de49f98bf4946cfaa5068,cd44d244f302709c84f21c56de437504,2947,453,0,dropped_off_at,2016-06-27 00:07:54,2016-06-27 00:07:54,2016,6,27,00:07:54,0,7,54,0
782134,d27b078b9f801a979bda2687ef91159a,eed00970f7bada9f6987babe9ae3c24a,5026,802,25,dropped_off_at,2016-06-27 00:10:30,2016-06-27 00:10:30,2016,6,27,00:10:30,0,10,30,0
693249,b6b8068eea005094bf1eeab9c35c9c11,f704ac3e1a9b92454c1577f859b7f220,38914,1704,0,dropped_off_at,2016-06-27 00:10:58,2016-06-27 00:10:58,2016,6,27,00:10:58,0,10,58,0
331679,5943b68c2fa8bcfd0add30691fd9136b,bf49073d4b4369bb0e08a2d36e1cd097,23035,1163,0,dropped_off_at,2016-06-27 00:20:32,2016-06-27 00:20:32,2016,6,27,00:20:32,0,20,32,0
924054,ffff51a71f2f185ec5e97d59dbcd7a78,f90966687aebca6cc9efcd9e42897b75,20668,1469,0,dropped_off_at,2016-06-27 00:26:35,2016-06-27 00:26:35,2016,6,27,00:26:35,0,26,35,0
319984,55bec90600d21bd3513366d218f2b2f2,dbbe52211b1ed034fcb384a045229ff5,36818,2146,0,dropped_off_at,2016-06-27 00:31:23,2016-06-27 00:31:23,2016,6,27,00:31:23,0,31,23,0
621609,a4463e077e248abcd96b8ee584e7fec5,3259c38ec805a2b74611f5e9d53f140f,13181,4346,50,dropped_off_at,2016-06-27 00:50:50,2016-06-27 00:50:50,2016,6,27,00:50:50,0,50,50,0

In [104]:
# df2.drop_duplicates('a', keep='last')

myother = result.drop_duplicates('driver_id', keep='last')
myother

,driver_id,ride_id,ride_distance,ride_duration,ride_prime_time,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds,wait_num
429739,6eb2e0f41fc9f1fbb70e7751035fdf87,3ad3bcd120d1eb8540313654b685f44f,1737,344,0,dropped_off_at,2016-03-30 17:45:36,2016-03-30 17:45:36,2016,3,30,17:45:36,17,45,36,0
715734,bd057e02f75c92917389d90bb215fe91,5bfe6a47cdc9fe4fcad19a77724098de,2325,417,0,dropped_off_at,2016-03-30 19:00:46,2016-03-30 19:00:46,2016,3,30,19:00:46,19,0,46,0
841329,e4f3a9d5cf57b9b518136afd9757f76d,96cf3d56317b19b1c1a9ca2e7801febc,1549,472,0,dropped_off_at,2016-03-31 10:15:33,2016-03-31 10:15:33,2016,3,31,10:15:33,10,15,33,0
405264,68b546b2f4102641d6774c1ce4f57457,b1c3a3ef705dcc52d7b9b937270a98d9,1404,307,50,dropped_off_at,2016-03-31 19:22:58,2016-03-31 19:22:58,2016,3,31,19:22:58,19,22,58,0
605829,9fa4b644d8b6ea510119808c37f22223,97136251844f0def36566cc6d81ab03a,4077,543,0,dropped_off_at,2016-04-05 22:58:52,2016-04-05 22:58:52,2016,4,5,22:58:52,22,58,52,0
51049,1110d496149d3d8c50276765924df831,04a34d399d1e8a9973e2fd16ca563f42,4338,1231,0,dropped_off_at,2016-04-07 12:51:41,2016-04-07 12:51:41,2016,4,7,12:51:41,12,51,41,0
707634,b8df3a1ffca045016321353536ac86cf,99b4d4268f15cbbd7b125b8b10e0d84e,3257,435,0,dropped_off_at,2016-04-07 23:47:20,2016-04-07 23:47:20,2016,4,7,23:47:20,23,47,20,0
576049,9835cfed2c02bee16b5f0eeac3b4926a,337d5c4dd2f33ec6a3c0e9c9833c7e79,1621,352,0,dropped_off_at,2016-04-08 07:05:17,2016-04-08 07:05:17,2016,4,8,07:05:17,7,5,17,0
219464,3b2dca5cc3db92a05ea35056887108b6,c3887288123989647dc171efc753bb0f,9687,1029,0,dropped_off_at,2016-04-09 21:15:18,2016-04-09 21:15:18,2016,4,9,21:15:18,21,15,18,0
515614,84e1a98ccf46774bc4f5c6374079dc07,5e3e6f3557d90501aef3a68ee792b22d,2515,510,0,dropped_off_at,2016-04-10 00:40:11,2016-04-10 00:40:11,2016,4,10,00:40:11,0,40,11,0
609514,a2334fdb829cf96fbae920df0cce1587,35d0110f5cfeac4337ffea37419215d0,43280,2208,0,dropped_off_at,2016-04-10 13:04:34,2016-04-10 13:04:34,2016,4,10,13:04:34,13,4,34,0
16234,0430df9a3eb327122c57ee3a64765000,9a7627f6c81fc64667e0a91d7f35ea90,7654,1145,25,dropped_off_at,2016-04-13 21:24:28,2016-04-13 21:24:28,2016,4,13,21:24:28,21,24,28,0
838694,e35d490b495edf857a448653e036bd44,54f476aa0cf8fc24bd361644ba010f80,3248,578,0,dropped_off_at,2016-04-14 19:48:10,2016-04-14 19:48:10,2016,4,14,19:48:10,19,48,10,0
833699,e1d2df8059744cac678fbdc113e9e697,9926c0ce8326e7f77232585e71991ebe,2001,428,0,dropped_off_at,2016-04-14 22:53:45,2016-04-14 22:53:45,2016,4,14,22:53:45,22,53,45,0
509009,838495eb3f025e512228480eae127522,0a5dddc8caeae61013d6d78a04894cb6,10171,1021,0,dropped_off_at,2016-04-15 00:15:26,2016-04-15 00:15:26,2016,4,15,00:15:26,0,15,26,0
813839,ddf9fad53fff9a2f2ded181e1144b47f,c2ec7717ff91ead97c84d993de4cc5e1,8526,549,0,dropped_off_at,2016-04-15 15:24:48,2016-04-15 15:24:48,2016,4,15,15:24:48,15,24,48,0
72859,173a168d2b8830525f59be85a35f0000,cdba7408af9947cbd4b903c0f31af75d,597,206,0,dropped_off_at,2016-04-15 18:52:36,2016-04-15 18:52:36,2016,4,15,18:52:36,18,52,36,0
716929,bd26a8a5910f6c87aed2fcce32782fae,1ea17208fbea8f7b9525516f2ebf17d0,1452,299,0,dropped_off_at,2016-04-17 08:11:30,2016-04-17 08:11:30,2016,4,17,08:11:30,8,11,30,0
525279,895c14bfd7d1e2c26aee6938703f32f8,3c23a54c1953fe69c47596fa372e8784,26810,2522,0,dropped_off_at,2016-04-18 10:32:43,2016-04-18 10:32:43,2016,4,18,10:32:43,10,32,43,0
780609,d1576672b9ddf17e405ad295e66048ba,bdd3f07e9edca901a64f45bc4e190488,2275,1233,150,dropped_off_at,2016-04-18 18:40:59,2016-04-18 18:40:59,2016,4,18,18:40:59,18,40,59,0
527284,89dab1d9f815cea34ce3612a6b7c0d51,e4f95a9f05335c376e35d5d6fe48e8d6,2681,496,0,dropped_off_at,2016-04-19 09:54:37,2016-04-19 09:54:37,2016,4,19,09:54:37,9,54,37,0
483274,7b625f643d0775f0ac4898e33235377b,97a32c326fe3be0ae23e47443a8bcce9,3465,611,0,dropped_off_at,2016-04-19 19:04:10,2016-04-19 19:04:10,2016,4,19,19:04:10,19,4,10,0
43569,0eff1404b137a5562642f0f706e59f25,7fd494ff9ef85a35aefe19802fb292c4,2220,490,0,dropped_off_at,2016-04-20 18:54:15,2016-04-20 18:54:15,2016,4,20,18:54:15,18,54,15,0
768749,ce577ac73e9022772835abf8d37e91d5,5ada7d439d66e6cdb3372a53a52429ac,17218,1185,25,dropped_off_at,2016-04-21 00:41:58,2016-04-21 00:41:58,2016,4,21,00:41:58,0,41,58,0
882004,f06398053a230bf914041eb897dc8d62,7dbe5a5e1ac0c53b57e8448df5119e03,3606,792,25,dropped_off_at,2016-04-21 10:54:39,2016-04-21 10:54:39,2016,4,21,10:54:39,10,54,39,0
73289,17c09e7e39d8ab4bb4e035061d43ecdd,190d4cb36852111ca26ffa0c035f21bd,1653,284,25,dropped_off_at,2016-04-21 16:59:55,2016-04-21 16:59:55,2016,4,21,16:59:55,16,59,55,0
768979,ce5b4b1624afd0dd514e8997a2a1ff1d,756394e1fa6faff631a917c000a5be46,2309,676,50,dropped_off_at,2016-04-22 15:00:19,2016-04-22 15:00:19,2016,4,22,15:00:19,15,0,19,0
183724,33b7762088cf5b82b8fe6fc291f93b6b,e60511d8834badaada4ef1a139aa073d,24945,1270,0,dropped_off_at,2016-04-23 09:28:49,2016-04-23 09:28:49,2016,4,23,09:28:49,9,28,49,0
488289,7c4bcea05c14431c65ef1d9cfa20ecb1,0d30a92a130bf1ca84a79720ba4ef105,3740,470,0,dropped_off_at,2016-04-23 10:08:40,2016-04-23 10:08:40,2016,4,23,10:08:40,10,8,40,0
798029,d7e035984d4fba2d14bc37f1992a061f,98278beb0d32e55b0d94dc1009b7108d,1388,176,0,dropped_off_at,2016-04-24 00:26:00,2016-04-24 00:26:00,2016,4,24,00:26:00,0,26,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872654,eef12344364d2a2e1e2d581287cf9cd8,f5fa193da05817a2e4e15b1257e96e93,16920,990,0,dropped_off_at,2016-06-26 23:38:46,2016-06-26 23:38:46,2016,6,26,23:38:46,23,38,46,0
251364,434adfc83c625f393595207cfff91ef2,b427726d49bc7ae7454ae4de39382c7a,1525,365,25,dropped_off_at,2016-06-26 23:38:58,2016-06-26 23:38:58,2016,6,26,23:38:58,23,38,58,0
95509,1b9ddecea8eb99bc37f9b0711546f1c0,9cb9848fb9410b2db674473ab383d6fc,3118,643,0,dropped_off_at,2016-06-26 23:39:21,2016-06-26 23:39:21,2016,6,26,23:39:21,23,39,21,0
136984,2678d03ea513d10988818e77c5915b75,cf01b4c54c02683a54ecc68e1ced4391,11716,906,25,dropped_off_at,2016-06-26 23:42:42,2016-06-26 23:42:42,2016,6,26,23:42:42,23,42,42,0
834244,e225e4363d4ef824640866378d49a878,5c2a2bc2db8375c8403f62ff299bfe6a,2381,478,25,dropped_off_at,2016-06-26 23:43:04,2016-06-26 23:43:04,2016,6,26,23:43:04,23,43,4,0
846114,e67fc482899bea76fa32d6274607140d,6e6df9973e13663b2c4ecc1fe3369d29,5793,509,0,dropped_off_at,2016-06-26 23:48:23,2016-06-26 23:48:23,2016,6,26,23:48:23,23,48,23,0
431259,6f107d977e357e3d22036cc447b354b0,7fcc1c80efdac3baa021e06196f9b8be,3510,521,0,dropped_off_at,2016-06-26 23:48:46,2016-06-26 23:48:46,2016,6,26,23:48:46,23,48,46,0
313979,53e554eb940176c64fa8ee10a394f835,4a9a2ad708ccf45bd0eeff6ddf172938,8009,1935,25,dropped_off_at,2016-06-26 23:49:04,2016-06-26 23:49:04,2016,6,26,23:49:04,23,49,4,0
654669,abc63585621a8cc49099bc9dde677f27,e01787972b563439b51c0df016afd698,15284,1078,50,dropped_off_at,2016-06-26 23:49:31,2016-06-26 23:49:31,2016,6,26,23:49:31,23,49,31,0
407804,68c4e63e9663a4bd8d4e435601a26a37,dac78b3bb43c8567f8d3e52ffad94b41,13235,1693,0,dropped_off_at,2016-06-26 23:49:45,2016-06-26 23:49:45,2016,6,26,23:49:45,23,49,45,0
804369,db63522a6a88af9b817df48e3f6bad15,7d8d0d061674ba91ad6dd26c3ae7555b,29811,1254,0,dropped_off_at,2016-06-26 23:50:36,2016-06-26 23:50:36,2016,6,26,23:50:36,23,50,36,0
340079,5bd37993cfff08be940348a466912238,e20139c44d479216ca414ab603a35994,2655,395,25,dropped_off_at,2016-06-26 23:50:44,2016-06-26 23:50:44,2016,6,26,23:50:44,23,50,44,0
374339,62c83d1a137771a5c82433c8b3f7fddb,7e5a08832aef6f42b6f8828901b18393,25801,2164,25,dropped_off_at,2016-06-26 23:53:00,2016-06-26 23:53:00,2016,6,26,23:53:00,23,53,0,0
128554,2494554e7702a28816717bc0cbf7d57b,ac323f1e3df2e4739f871e762770aeb5,1922,427,0,dropped_off_at,2016-06-26 23:57:13,2016-06-26 23:57:13,2016,6,26,23:57:13,23,57,13,0
302949,50eadd94fd0152fd0638a915061c4c94,c91436292acc91ba5ad3acf8e8e81a50,4088,528,0,dropped_off_at,2016-06-26 23:57:30,2016-06-26 23:57:30,2016,6,26,23:57:30,23,57,30,0
227679,3caf85a7d6b8f5615fbc21e8310af584,c3d72d35b8213d432f107b2fbac849cd,1407,260,0,dropped_off_at,2016-06-26 23:58:20,2016-06-26 23:58:20,2016,6,26,23:58:20,23,58,20,0
417599,6b65c06851e944351dd285a1eb729499,690fe116339622f72af07f2f269b8521,5271,420,0,dropped_off_at,2016-06-26 23:59:25,2016-06-26 23:59:25,2016,6,26,23:59:25,23,59,25,0
760374,cbba49117a03fd2f578022eab904dced,cb283287700d34c276682909c36aa99f,6319,568,25,dropped_off_at,2016-06-27 00:01:35,2016-06-27 00:01:35,2016,6,27,00:01:35,0,1,35,0
726459,c0640121b56458ccc0d2892067bc463b,e015a43686af84d5c1ae6f56dd1122aa,3984,890,0,dropped_off_at,2016-06-27 00:02:01,2016-06-27 00:02:01,2016,6,27,00:02:01,0,2,1,0
847374,e76529a86a5efc221a88a6c91a75ea59,ba31b0623e6f7c35033c107553376a35,8065,764,0,dropped_off_at,2016-06-27 00:04:29,2016-06-27 00:04:29,2016,6,27,00:04:29,0,4,29,0
21954,0656192a402808805282e60761bda088,e51093e307953ecf29061fb83aee3081,3214,419,0,dropped_off_at,2016-06-27 00:05:27,2016-06-27 00:05:27,2016,6,27,00:05:27,0,5,27,0
545579,8dbfef11a650dd9658ca0c6f70b84f88,311542541524c0d356fa8d7fc229baae,2546,388,25,dropped_off_at,2016-06-27 00:05:30,2016-06-27 00:05:30,2016,6,27,00:05:30,0,5,30,0
859539,ec78920915122cbe500fcb475a8fb5d3,8a18c5c67f4a7bb8f1ee3f482eb61727,11262,713,0,dropped_off_at,2016-06-27 00:06:20,2016-06-27 00:06:20,2016,6,27,00:06:20,0,6,20,0
403124,689bdf87fb2de49f98bf4946cfaa5068,cd44d244f302709c84f21c56de437504,2947,453,0,dropped_off_at,2016-06-27 00:07:54,2016-06-27 00:07:54,2016,6,27,00:07:54,0,7,54,0
782134,d27b078b9f801a979bda2687ef91159a,eed00970f7bada9f6987babe9ae3c24a,5026,802,25,dropped_off_at,2016-06-27 00:10:30,2016-06-27 00:10:30,2016,6,27,00:10:30,0,10,30,0
693249,b6b8068eea005094bf1eeab9c35c9c11,f704ac3e1a9b92454c1577f859b7f220,38914,1704,0,dropped_off_at,2016-06-27 00:10:58,2016-06-27 00:10:58,2016,6,27,00:10:58,0,10,58,0
331679,5943b68c2fa8bcfd0add30691fd9136b,bf49073d4b4369bb0e08a2d36e1cd097,23035,1163,0,dropped_off_at,2016-06-27 00:20:32,2016-06-27 00:20:32,2016,6,27,00:20:32,0,20,32,0
924054,ffff51a71f2f185ec5e97d59dbcd7a78,f90966687aebca6cc9efcd9e42897b75,20668,1469,0,dropped_off_at,2016-06-27 00:26:35,2016-06-27 00:26:35,2016,6,27,00:26:35,0,26,35,0
319984,55bec90600d21bd3513366d218f2b2f2,dbbe52211b1ed034fcb384a045229ff5,36818,2146,0,dropped_off_at,2016-06-27 00:31:23,2016-06-27 00:31:23,2016,6,27,00:31:23,0,31,23,0
621609,a4463e077e248abcd96b8ee584e7fec5,3259c38ec805a2b74611f5e9d53f140f,13181,4346,50,dropped_off_at,2016-06-27 00:50:50,2016-06-27 00:50:50,2016,6,27,00:50:50,0,50,50,0

In [96]:
len(driver_ids_df)

937

In [217]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import os
from datetime import datetime

driver_ids =driver_ids_df
ride_ids = ride_ids_df
timestamps = ride_timestamps_df


driver_prime = ride_ids[["driver_id", "ride_prime_time"]]
driver_prime_count = driver_prime.groupby('ride_prime_time').count()
driv_ride = ride_ids[['driver_id', 'ride_id']]
uniq_rides = timestamps[timestamps['event'] == 'accepted_at'][['ride_id', 'timestamp']]

driv_ride_time = pd.merge(uniq_rides, driv_ride, on='ride_id')

driv_ride_time.head()

latest_ride = driv_ride_time.groupby('driver_id').max()
latest_ride.rename(columns={'timestamp':'latest_ride'}, inplace=True)
latest_ride.drop('ride_id', axis=1, inplace=True)

oldest_ride = driv_ride_time.groupby('driver_id').min()
oldest_ride.rename(columns={'timestamp':'oldest_ride'}, inplace=True)
oldest_ride.drop('ride_id', axis=1, inplace=True)
oldest_ride

retention_raw = pd.merge(oldest_ride, latest_ride, on='driver_id')

to_date_obj = lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S').date()
oldest_date_obj = retention_raw['oldest_ride'].apply(to_date_obj)
latest_date_obj = retention_raw['latest_ride'].apply(to_date_obj)
retention = pd.concat([oldest_date_obj,latest_date_obj], axis=1)

retention['retention_period'] = retention['latest_ride'] - retention['oldest_ride']

retention.head()

                                 oldest_ride latest_ride retention_period
driver_id
002be0ffdc997bd5c50703158b7c2491  2016-03-29  2016-06-23          86 days
007f0389f9c7b03ef97098422f902e62  2016-03-29  2016-06-22          85 days
011e5c5dfc5c2c92501b8b24d47509bc  2016-04-05  2016-06-12          68 days
0152a2f305e71d26cc964f8d4411add9  2016-04-25  2016-06-26          62 days
01674381af7edd264113d4e6ed55ecda  2016-04-29  2016-06-24          56 days

In [222]:
myret = list(retention["retention_period"].dt.days)

retention["retention_int"] = myret

In [121]:
# given ride id, driver id, and the hours
# of the rides find the hour that this driver mostly drives at. 

common_time = pd.merge(driver_ids_df, ride_ids, on = "driver_id")
common_time = pd.merge(common_time, ride_timestamps_df, on = "ride_id")

common_time

,driver_id,driver_onboard_date,ride_id,ride_distance,ride_duration,ride_prime_time,event,timestamp,timestamp_c,Year,Month,Date,Other,Hour,Minutes,Seconds,wait_num
0,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,006d61cf7446e682f7bc50b0f8a5bea5,1811,327,50,requested_at,2016-04-23 02:13:50,2016-04-23 02:13:50,2016,4,23,02:13:50,2,13,50,0
1,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,006d61cf7446e682f7bc50b0f8a5bea5,1811,327,50,accepted_at,2016-04-23 02:14:15,2016-04-23 02:14:15,2016,4,23,02:14:15,2,14,15,0
2,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,006d61cf7446e682f7bc50b0f8a5bea5,1811,327,50,arrived_at,2016-04-23 02:16:36,2016-04-23 02:16:36,2016,4,23,02:16:36,2,16,36,0
3,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,006d61cf7446e682f7bc50b0f8a5bea5,1811,327,50,picked_up_at,2016-04-23 02:16:40,2016-04-23 02:16:40,2016,4,23,02:16:40,2,16,40,0
4,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,006d61cf7446e682f7bc50b0f8a5bea5,1811,327,50,dropped_off_at,2016-04-23 02:22:07,2016-04-23 02:22:07,2016,4,23,02:22:07,2,22,7,0
5,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,01b522c5c3a756fbdb12e95e87507eda,3362,809,0,requested_at,2016-03-29 19:00:49,2016-03-29 19:00:49,2016,3,29,19:00:49,19,0,49,0
6,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,01b522c5c3a756fbdb12e95e87507eda,3362,809,0,accepted_at,2016-03-29 19:00:52,2016-03-29 19:00:52,2016,3,29,19:00:52,19,0,52,0
7,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,01b522c5c3a756fbdb12e95e87507eda,3362,809,0,arrived_at,2016-03-29 19:03:57,2016-03-29 19:03:57,2016,3,29,19:03:57,19,3,57,0
8,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,01b522c5c3a756fbdb12e95e87507eda,3362,809,0,picked_up_at,2016-03-29 19:04:01,2016-03-29 19:04:01,2016,3,29,19:04:01,19,4,1,0
9,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,01b522c5c3a756fbdb12e95e87507eda,3362,809,0,dropped_off_at,2016-03-29 19:17:30,2016-03-29 19:17:30,2016,3,29,19:17:30,19,17,30,0
10,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,029227c4c2971ce69ff2274dc798ef43,3282,572,0,requested_at,2016-06-21 11:56:31,2016-06-21 11:56:31,2016,6,21,11:56:31,11,56,31,0
11,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,029227c4c2971ce69ff2274dc798ef43,3282,572,0,accepted_at,2016-06-21 11:56:39,2016-06-21 11:56:39,2016,6,21,11:56:39,11,56,39,0
12,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,029227c4c2971ce69ff2274dc798ef43,3282,572,0,arrived_at,2016-06-21 12:01:32,2016-06-21 12:01:32,2016,6,21,12:01:32,12,1,32,0
13,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,029227c4c2971ce69ff2274dc798ef43,3282,572,0,picked_up_at,2016-06-21 12:01:35,2016-06-21 12:01:35,2016,6,21,12:01:35,12,1,35,0
14,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,029227c4c2971ce69ff2274dc798ef43,3282,572,0,dropped_off_at,2016-06-21 12:11:07,2016-06-21 12:11:07,2016,6,21,12:11:07,12,11,7,0
15,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034e861343a63ac3c18a9ceb1ce0ac69,65283,3338,25,requested_at,2016-05-19 09:15:29,2016-05-19 09:15:29,2016,5,19,09:15:29,9,15,29,0
16,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034e861343a63ac3c18a9ceb1ce0ac69,65283,3338,25,accepted_at,2016-05-19 09:15:33,2016-05-19 09:15:33,2016,5,19,09:15:33,9,15,33,0
17,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034e861343a63ac3c18a9ceb1ce0ac69,65283,3338,25,arrived_at,2016-05-19 09:18:20,2016-05-19 09:18:20,2016,5,19,09:18:20,9,18,20,0
18,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034e861343a63ac3c18a9ceb1ce0ac69,65283,3338,25,picked_up_at,2016-05-19 09:18:20,2016-05-19 09:18:20,2016,5,19,09:18:20,9,18,20,0
19,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034e861343a63ac3c18a9ceb1ce0ac69,65283,3338,25,dropped_off_at,2016-05-19 10:13:58,2016-05-19 10:13:58,2016,5,19,10:13:58,10,13,58,0
20,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034f2e614a2f9fc7f1c2f77647d1b981,4115,823,100,requested_at,2016-04-20 22:05:30,2016-04-20 22:05:30,2016,4,20,22:05:30,22,5,30,0
21,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034f2e614a2f9fc7f1c2f77647d1b981,4115,823,100,accepted_at,2016-04-20 22:05:32,2016-04-20 22:05:32,2016,4,20,22:05:32,22,5,32,0
22,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034f2e614a2f9fc7f1c2f77647d1b981,4115,823,100,arrived_at,2016-04-20 22:07:03,2016-04-20 22:07:03,2016,4,20,22:07:03,22,7,3,0
23,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034f2e614a2f9fc7f1c2f77647d1b981,4115,823,100,picked_up_at,2016-04-20 22:07:02,2016-04-20 22:07:02,2016,4,20,22:07:02,22,7,2,0
24,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,034f2e614a2f9fc7f1c2f77647d1b981,4115,823,100,dropped_off_at,2016-04-20 22:20:45,2016-04-20 22:20:45,2016,4,20,22:20:45,22,20,45,0
25,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,03d6b9d80b8a96135cb9b25178e9e203,4832,917,100,requested_at,2016-06-21 08:29:17,2016-06-21 08:29:17,2016,6,21,08:29:17,8,29,17,0
26,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,03d6b9d80b8a96135cb9b25178e9e203,4832,917,100,accepted_at,2016-06-21 08:29:24,2016-06-21 08:29:24,2016,6,21,08:29:24,8,29,24,0
27,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,03d6b9d80b8a96135cb9b25178e9e203,4832,917,100,arrived_at,2016-06-21 08:35:33,2016-06-21 08:35:33,2016,6,21,08:35:33,8,35,33,0
28,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,03d6b9d80b8a96135cb9b25178e9e203,4832,917,100,picked_up_at,2016-06-21 08:35:36,2016-06-21 08:35:36,2016,6,21,08:35:36,8,35,36,0
29,002be0ffdc997bd5c50703158b7c2491,2016-03-29 00:00:00,03d6b9d80b8a96135cb9b25178e9e203,4832,917,100,dropped_off_at,2016-06-21 08:50:53,2016-06-21 08:50:53,2016,6,21,08:50:53,8,50,53,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921010,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fb93e23e2a9be7a50bb6c50d05af9a1e,4391,1017,25,requested_at,2016-06-12 22:17:08,2016-06-12 22:17:08,2016,6,12,22:17:08,22,17,8,0
921011,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fb93e23e2a9be7a50bb6c50d05af9a1e,4391,1017,25,accepted_at,2016-06-12 22:17:09,2016-06-12 22:17:09,2016,6,12,22:17:09,22,17,9,0
921012,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fb93e23e2a9be7a50bb6c50d05af9a1e,4391,1017,25,arrived_at,2016-06-12 22:22:21,2016-06-12 22:22:21,2016,6,12,22:22:21,22,22,21,0
921013,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fb93e23e2a9be7a50bb6c50d05af9a1e,4391,1017,25,picked_up_at,2016-06-12 22:22:23,2016-06-12 22:22:23,2016,6,12,22:22:23,22,22,23,0
921014,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fb93e23e2a9be7a50bb6c50d05af9a1e,4391,1017,25,dropped_off_at,2016-06-12 22:39:20,2016-06-12 22:39:20,2016,6,12,22:39:20,22,39,20,0
921015,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fc717192b3512767269ff5a54b97af05,10127,1336,0,requested_at,2016-06-18 01:14:52,2016-06-18 01:14:52,2016,6,18,01:14:52,1,14,52,0
921016,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fc717192b3512767269ff5a54b97af05,10127,1336,0,accepted_at,2016-06-18 01:15:52,2016-06-18 01:15:52,2016,6,18,01:15:52,1,15,52,0
921017,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fc717192b3512767269ff5a54b97af05,10127,1336,0,arrived_at,2016-06-18 01:21:11,2016-06-18 01:21:11,2016,6,18,01:21:11,1,21,11,0
921018,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fc717192b3512767269ff5a54b97af05,10127,1336,0,picked_up_at,2016-06-18 01:21:14,2016-06-18 01:21:14,2016,6,18,01:21:14,1,21,14,0
921019,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fc717192b3512767269ff5a54b97af05,10127,1336,0,dropped_off_at,2016-06-18 01:43:30,2016-06-18 01:43:30,2016,6,18,01:43:30,1,43,30,0
921020,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fd6fa5f9265d2cf83936ead663f9e0e7,1908,445,0,requested_at,2016-06-23 23:51:55,2016-06-23 23:51:55,2016,6,23,23:51:55,23,51,55,0
921021,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fd6fa5f9265d2cf83936ead663f9e0e7,1908,445,0,accepted_at,2016-06-23 23:52:08,2016-06-23 23:52:08,2016,6,23,23:52:08,23,52,8,0
921022,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fd6fa5f9265d2cf83936ead663f9e0e7,1908,445,0,arrived_at,2016-06-23 23:59:04,2016-06-23 23:59:04,2016,6,23,23:59:04,23,59,4,0
921023,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fd6fa5f9265d2cf83936ead663f9e0e7,1908,445,0,picked_up_at,2016-06-23 23:59:08,2016-06-23 23:59:08,2016,6,23,23:59:08,23,59,8,0
921024,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fd6fa5f9265d2cf83936ead663f9e0e7,1908,445,0,dropped_off_at,2016-06-24 00:06:33,2016-06-24 00:06:33,2016,6,24,00:06:33,0,6,33,0
921025,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fe0857c43025264d337dfe1d8463e503,4039,875,0,requested_at,2016-05-31 19:26:34,2016-05-31 19:26:34,2016,5,31,19:26:34,19,26,34,0
921026,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fe0857c43025264d337dfe1d8463e503,4039,875,0,accepted_at,2016-05-31 19:26:42,2016-05-31 19:26:42,2016,5,31,19:26:42,19,26,42,0
921027,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fe0857c43025264d337dfe1d8463e503,4039,875,0,arrived_at,2016-05-31 19:29:08,2016-05-31 19:29:08,2016,5,31,19:29:08,19,29,8,0
921028,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fe0857c43025264d337dfe1d8463e503,4039,875,0,picked_up_at,2016-05-31 19:29:11,2016-05-31 19:29:11,2016,5,31,19:29:11,19,29,11,0
921029,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,fe0857c43025264d337dfe1d8463e503,4039,875,0,dropped_off_at,2016-05-31 19:43:46,2016-05-31 19:43:46,2016,5,31,19:43:46,19,43,46,0
921030,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff0db0ca4557bf5b05b4da6f660a1ac1,4760,777,0,requested_at,2016-05-15 00:51:53,2016-05-15 00:51:53,2016,5,15,00:51:53,0,51,53,0
921031,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff0db0ca4557bf5b05b4da6f660a1ac1,4760,777,0,accepted_at,2016-05-15 00:51:59,2016-05-15 00:51:59,2016,5,15,00:51:59,0,51,59,0
921032,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff0db0ca4557bf5b05b4da6f660a1ac1,4760,777,0,arrived_at,2016-05-15 00:52:05,2016-05-15 00:52:05,2016,5,15,00:52:05,0,52,5,0
921033,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff0db0ca4557bf5b05b4da6f660a1ac1,4760,777,0,picked_up_at,2016-05-15 00:52:07,2016-05-15 00:52:07,2016,5,15,00:52:07,0,52,7,0
921034,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff0db0ca4557bf5b05b4da6f660a1ac1,4760,777,0,dropped_off_at,2016-05-15 01:05:04,2016-05-15 01:05:04,2016,5,15,01:05:04,1,5,4,0
921035,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff7dc29693f8c79ff103d350a7b6c157,3751,889,100,requested_at,2016-05-15 21:08:47,2016-05-15 21:08:47,2016,5,15,21:08:47,21,8,47,0
921036,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff7dc29693f8c79ff103d350a7b6c157,3751,889,100,accepted_at,2016-05-15 21:08:55,2016-05-15 21:08:55,2016,5,15,21:08:55,21,8,55,0
921037,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff7dc29693f8c79ff103d350a7b6c157,3751,889,100,arrived_at,2016-05-15 21:11:26,2016-05-15 21:11:26,2016,5,15,21:11:26,21,11,26,0
921038,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff7dc29693f8c79ff103d350a7b6c157,3751,889,100,picked_up_at,2016-05-15 21:11:29,2016-05-15 21:11:29,2016,5,15,21:11:29,21,11,29,0
921039,ffff51a71f2f185ec5e97d59dbcd7a78,2016-05-04 00:00:00,ff7dc29693f8c79ff103d350a7b6c157,3751,889,100,dropped_off_at,2016-05-15 21:26:18,2016-05-15 21:26:18,2016,5,15,21:26:18,21,26,18,0

In [188]:
my_time = common_time[["driver_id", "ride_id", "Hour", "ride_prime_time"]]
my_time

,driver_id,ride_id,Hour,ride_prime_time
0,002be0ffdc997bd5c50703158b7c2491,006d61cf7446e682f7bc50b0f8a5bea5,2,50
1,002be0ffdc997bd5c50703158b7c2491,006d61cf7446e682f7bc50b0f8a5bea5,2,50
2,002be0ffdc997bd5c50703158b7c2491,006d61cf7446e682f7bc50b0f8a5bea5,2,50
3,002be0ffdc997bd5c50703158b7c2491,006d61cf7446e682f7bc50b0f8a5bea5,2,50
4,002be0ffdc997bd5c50703158b7c2491,006d61cf7446e682f7bc50b0f8a5bea5,2,50
5,002be0ffdc997bd5c50703158b7c2491,01b522c5c3a756fbdb12e95e87507eda,19,0
6,002be0ffdc997bd5c50703158b7c2491,01b522c5c3a756fbdb12e95e87507eda,19,0
7,002be0ffdc997bd5c50703158b7c2491,01b522c5c3a756fbdb12e95e87507eda,19,0
8,002be0ffdc997bd5c50703158b7c2491,01b522c5c3a756fbdb12e95e87507eda,19,0
9,002be0ffdc997bd5c50703158b7c2491,01b522c5c3a756fbdb12e95e87507eda,19,0
10,002be0ffdc997bd5c50703158b7c2491,029227c4c2971ce69ff2274dc798ef43,11,0
11,002be0ffdc997bd5c50703158b7c2491,029227c4c2971ce69ff2274dc798ef43,11,0
12,002be0ffdc997bd5c50703158b7c2491,029227c4c2971ce69ff2274dc798ef43,12,0
13,002be0ffdc997bd5c50703158b7c2491,029227c4c2971ce69ff2274dc798ef43,12,0
14,002be0ffdc997bd5c50703158b7c2491,029227c4c2971ce69ff2274dc798ef43,12,0
15,002be0ffdc997bd5c50703158b7c2491,034e861343a63ac3c18a9ceb1ce0ac69,9,25
16,002be0ffdc997bd5c50703158b7c2491,034e861343a63ac3c18a9ceb1ce0ac69,9,25
17,002be0ffdc997bd5c50703158b7c2491,034e861343a63ac3c18a9ceb1ce0ac69,9,25
18,002be0ffdc997bd5c50703158b7c2491,034e861343a63ac3c18a9ceb1ce0ac69,9,25
19,002be0ffdc997bd5c50703158b7c2491,034e861343a63ac3c18a9ceb1ce0ac69,10,25
20,002be0ffdc997bd5c50703158b7c2491,034f2e614a2f9fc7f1c2f77647d1b981,22,100
21,002be0ffdc997bd5c50703158b7c2491,034f2e614a2f9fc7f1c2f77647d1b981,22,100
22,002be0ffdc997bd5c50703158b7c2491,034f2e614a2f9fc7f1c2f77647d1b981,22,100
23,002be0ffdc997bd5c50703158b7c2491,034f2e614a2f9fc7f1c2f77647d1b981,22,100
24,002be0ffdc997bd5c50703158b7c2491,034f2e614a2f9fc7f1c2f77647d1b981,22,100
25,002be0ffdc997bd5c50703158b7c2491,03d6b9d80b8a96135cb9b25178e9e203,8,100
26,002be0ffdc997bd5c50703158b7c2491,03d6b9d80b8a96135cb9b25178e9e203,8,100
27,002be0ffdc997bd5c50703158b7c2491,03d6b9d80b8a96135cb9b25178e9e203,8,100
28,002be0ffdc997bd5c50703158b7c2491,03d6b9d80b8a96135cb9b25178e9e203,8,100
29,002be0ffdc997bd5c50703158b7c2491,03d6b9d80b8a96135cb9b25178e9e203,8,100
...,...,...,...,...
921010,ffff51a71f2f185ec5e97d59dbcd7a78,fb93e23e2a9be7a50bb6c50d05af9a1e,22,25
921011,ffff51a71f2f185ec5e97d59dbcd7a78,fb93e23e2a9be7a50bb6c50d05af9a1e,22,25
921012,ffff51a71f2f185ec5e97d59dbcd7a78,fb93e23e2a9be7a50bb6c50d05af9a1e,22,25
921013,ffff51a71f2f185ec5e97d59dbcd7a78,fb93e23e2a9be7a50bb6c50d05af9a1e,22,25
921014,ffff51a71f2f185ec5e97d59dbcd7a78,fb93e23e2a9be7a50bb6c50d05af9a1e,22,25
921015,ffff51a71f2f185ec5e97d59dbcd7a78,fc717192b3512767269ff5a54b97af05,1,0
921016,ffff51a71f2f185ec5e97d59dbcd7a78,fc717192b3512767269ff5a54b97af05,1,0
921017,ffff51a71f2f185ec5e97d59dbcd7a78,fc717192b3512767269ff5a54b97af05,1,0
921018,ffff51a71f2f185ec5e97d59dbcd7a78,fc717192b3512767269ff5a54b97af05,1,0
921019,ffff51a71f2f185ec5e97d59dbcd7a78,fc717192b3512767269ff5a54b97af05,1,0
921020,ffff51a71f2f185ec5e97d59dbcd7a78,fd6fa5f9265d2cf83936ead663f9e0e7,23,0
921021,ffff51a71f2f185ec5e97d59dbcd7a78,fd6fa5f9265d2cf83936ead663f9e0e7,23,0
921022,ffff51a71f2f185ec5e97d59dbcd7a78,fd6fa5f9265d2cf83936ead663f9e0e7,23,0
921023,ffff51a71f2f185ec5e97d59dbcd7a78,fd6fa5f9265d2cf83936ead663f9e0e7,23,0
921024,ffff51a71f2f185ec5e97d59dbcd7a78,fd6fa5f9265d2cf83936ead663f9e0e7,0,0
921025,ffff51a71f2f185ec5e97d59dbcd7a78,fe0857c43025264d337dfe1d8463e503,19,0
921026,ffff51a71f2f185ec5e97d59dbcd7a78,fe0857c43025264d337dfe1d8463e503,19,0
921027,ffff51a71f2f185ec5e97d59dbcd7a78,fe0857c43025264d337dfe1d8463e503,19,0
921028,ffff51a71f2f185ec5e97d59dbcd7a78,fe0857c43025264d337dfe1d8463e503,19,0
921029,ffff51a71f2f185ec5e97d59dbcd7a78,fe0857c43025264d337dfe1d8463e503,19,0
921030,ffff51a71f2f185ec5e97d59dbcd7a78,ff0db0ca4557bf5b05b4da6f660a1ac1,0,0
921031,ffff51a71f2f185ec5e97d59dbcd7a78,ff0db0ca4557bf5b05b4da6f660a1ac1,0,0
921032,ffff51a71f2f185ec5e97d59dbcd7a78,ff0db0ca4557bf5b05b4da6f660a1ac1,0,0
921033,ffff51a71f2f185ec5e97d59dbcd7a78,ff0db0ca4557bf5b05b4da6f660a1ac1,0,0
921034,ffff51a71f2f185ec5e97d59dbcd7a78,ff0db0ca4557bf5b05b4da6f660a1ac1,1,0
921035,ffff51a71f2f185ec5e97d59dbcd7a78,ff7dc29693f8c79ff103d350a7b6c157,21,100
921036,ffff51a71f2f185ec5e97d59dbcd7a78,ff7dc29693f8c79ff103d350a7b6c157,21,100
921037,ffff51a71f2f185ec5e97d59dbcd7a78,ff7dc29693f8c79ff103d350a7b6c157,21,100
921038,ffff51a71f2f185ec5e97d59dbcd7a78,ff7dc29693f8c79ff103d350a7b6c157,21,100
921039,ffff51a71f2f185ec5e97d59dbcd7a78,ff7dc29693f8c79ff103d350a7b6c157,21,100

In [195]:
mode_hour = my_time.groupby(["driver_id","ride_prime_time"])["Hour"].agg(pd.Series.mode).to_frame()
mode_hour

                                                                     Hour
driver_id                        ride_prime_time
002be0ffdc997bd5c50703158b7c2491 0                                     20
                                 25                                    18
                                 50                                    22
                                 75                                    22
                                 100                                    8
                                 150                              [2, 21]
007f0389f9c7b03ef97098422f902e62 0                                     20
                                 25                                    21
                                 50                                    21
                                 75                                    17
011e5c5dfc5c2c92501b8b24d47509bc 0                                     19
                                 25                                    18
                                 50                              [11, 20]
                                 75                       [0, 16, 19, 20]
0152a2f305e71d26cc964f8d4411add9 0                                      0
                                 25                                     8
                                 50                                    22
                                 75                                     8
                                 100                                    2
01674381af7edd264113d4e6ed55ecda 0                                     10
                                 25                                     8
                                 50                                    12
                                 75                                     8
                                 100                                    8
                                 150                               [7, 8]
0213f8b59219e32142711992ca4ec01f 0                                     21
                                 25                                    22
                                 50                                    22
                                 75               [2, 18, 19, 20, 21, 23]
                                 100                                   19
...                                                                   ...
ff419a3476e21e269e340b5f1f05414e 0                                     11
                                 25                                    13
                                 50                                    17
                                 75                                    11
                                 100                                   18
                                 150                                    2
ff714a67ba8c6a108261cd81e3b77f3a 0                                      7
                                 25                                     8
                                 50                                     8
                                 75                                     8
                                 100                                   17
                                 150                               [8, 9]
fff482c704d36a1afe8b8978d5486283 0                                     13
                                 25                                    14
                                 50                                    11
fffecccc49436c5389075b13209f0dfa 0                                     10
                                 25                                    18
                                 50                                    20
                                 75                                    18
                                 100                                   18
                                 150                                    8
                                 200                                    8
ffff51a71f2f185ec5e97d59dbcd7a78 0                                      1
                                 25                                    19
                                 50                                     2
                                 75                                    23
                                 100                                    9
                                 150                               [1, 8]
                                 200                                   23
                                 300                                    9

[4835 rows x 1 columns]

In [182]:
name_list = list(mode_hour.ride_prime_time)

name_list

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 25,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 25,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [183]:
mode_hour["average prime time"] = name_list

In [180]:
mode_hour

                                  ride_prime_time  average prime time
driver_id
002be0ffdc997bd5c50703158b7c2491        19.404332           19.404332
007f0389f9c7b03ef97098422f902e62        20.161290           20.161290
011e5c5dfc5c2c92501b8b24d47509bc        19.852941           19.852941
0152a2f305e71d26cc964f8d4411add9        10.732984           10.732984
01674381af7edd264113d4e6ed55ecda        12.533333           12.533333
0213f8b59219e32142711992ca4ec01f        10.312500           10.312500
021e5cd15ef0bb3ec20a12af99e142b3        22.641509           22.641509
0258e250ca195cc6258cbdc75aecd853        11.589404           11.589404
028b5a4dcd7f4924ebfabcf2e814c014        10.950413           10.950413
02d6a6b8a6da15fc219a9570f7ebbe78         3.629032            3.629032
02e440f6c209206375833cef02e0cbae        14.285714           14.285714
036f3d94e7c65e4e3574822d31c72656        12.745098           12.745098
039c5afbca8e03e4c18d9c8ea94140ac        11.842105           11.842105
039da9c077e17af98ca8530e4d7975f1        22.348485           22.348485
03f2b5c74cb89f39e58711699e76bf39        14.798206           14.798206
03f5278eb43475aa6790f5be32463755        18.851351           18.851351
0430df9a3eb327122c57ee3a64765000         7.558140            7.558140
04c4ffa5a385eab86fa7e422263d2999        26.363636           26.363636
04d686ef2fba281e395992a28f14fdd3        15.015723           15.015723
052bba06c5fc0bdea4bc2f9cb92b37c7        15.178571           15.178571
059ed570673c2d15ca11dd6b3a25513b        10.156250           10.156250
05addf442c147875efa5cf53453ad47b        23.982558           23.982558
05bad02e08c7f849e91dc1259da8b4ec        16.847826           16.847826
0656192a402808805282e60761bda088        15.634921           15.634921
06b1ba06e5505f8218ec8686498f990a        27.272727           27.272727
06c848ab3a7fc5421e82e98850a81710        12.750000           12.750000
07dd442e3e0b9f0f9b0d69c7b47cbb06         9.877622            9.877622
07e6a2fdaadc640cca9a7bec41351065        17.045455           17.045455
081d8ba3bc9a00a481df02bd9d0a4c53        15.104167           15.104167
0822973f3e812a68a867962dbbd37f5d        15.972222           15.972222
...                                           ...                 ...
f696de645de36b56677457d2d3136524        21.551724           21.551724
f758703e18f588f2370783f8b779e664        12.903226           12.903226
f7858e1e354a9fa26b3055bc12a4ee5b        10.806075           10.806075
f86eb77e1cefe28e9f0e9d3775fae261         9.000000            9.000000
f91254f1c1b3112ef3464e477d23c9e8        35.344828           35.344828
f98673773627b4b8d152e2b168b85bb2        10.714286           10.714286
f9aa6d69d74e786544027a1ab3049f44        26.937500           26.937500
fac81ea6cbd540c89c7eee17e851a233         9.000000            9.000000
faebff3d5429ff2036c125a91df765c8         1.562500            1.562500
fb83fc6555a4f700fd92630d9fcb9cea        17.500000           17.500000
fb903879c556260ae2604ae0c45cb92a        21.444954           21.444954
fba8372d56b91b1bff7b71d970b5af58         9.638554            9.638554
fbe0433e5b1a3db9dc9d6ed21efc6148        25.000000           25.000000
fc3504d2efaaaa976a33b3c856927155         8.142202            8.142202
fc83b793850ea70d9e898afd0b3ef592        17.653061           17.653061
fd2130d0d215069168dc2f79c1f5ae44        18.806647           18.806647
fd39748ba122e84e9ac492e6fb7c7a05        16.950464           16.950464
fd831ca1d79ae5c6fc3a679a22e5b8cf        21.052632           21.052632
fda96e6cd3395dfae3e59cd4ac95f7d7        24.623116           24.623116
fdbee494c73577d5b1266d1fec5c6c9a         8.510638            8.510638
fde60697758e68d617f471e49f65db75        17.968750           17.968750
fdff1a7205bc3b9ab1dc5dc223782fc5         9.466019            9.466019
fe35f74209d1056dd315ddb17681203d        15.284360           15.284360
fe469488a23d4bdda47b83a659dcc103        16.782007           16.782007
fed19d671569afe8a2f9fa0953dd25ca        21.969697           21.969697
ff419a3476e21e269e340b5f1f05414e        12.809917           12.809917
ff714a67ba8c6a108261cd81e3b77f3a        17.783505           17.783505
fff482c704d36a1afe8b8978d5486283         5.000000            5.000000
fffecccc49436c5389075b13209f0dfa        29.679803           29.679803
ffff51a71f2f185ec5e97d59dbcd7a78        20.075758           20.075758

[837 rows x 2 columns]

NameError: name 'with_prime' is not defined